export const LOCALES = [
  { code: 'zh-Hant', label: '繁體中文', short: '繁' },
  { code: 'zh-Hans', label: '简体中文', short: '简' },
  { code: 'en', label: 'English', short: 'EN' },
]

export const STRINGS = {
  en: {
    nav: {
      home: 'Home',
      community: 'Community',
      about: 'About',
      news: 'News',
      help: 'Help',
      volunteer: 'Volunteer',
      give: 'Give',
      donate: 'Donate',
      login: 'Log In',
      myImpact: 'My Impact',
      admin: 'Admin',
      easyRead: 'Easy Read',
      language: 'Language',
      skipToContent: 'Skip to content',
      askForHelp: 'Ask for help',
      easyReadBanner: 'Easy Read is on — larger text, clearer buttons.',
      easyReadTurnOff: 'Turn off',
    },
    homeSections: {
      navLabel: 'Page sections',
    },
    news: {
      eyebrow: 'Newsroom',
      title: 'Latest from Love 21',
      subhead: 'Announcements, explainers and our annual reporting.',
      readMore: 'Read the full story',
      readingTime: '{n} min read',
      backToNews: 'Back to home',
      notFound: 'We could not find that story.',
      loadFailed: 'That story could not be loaded — please try again.',
      categories: {
        news: 'News',
        education: 'Explainer',
        report: 'Report',
      },
      mythLabel: 'Myth',
      factLabel: 'Fact',
      embedFallback: 'View this post on Instagram',
    },
    hero: {
      eyebrow: '#Somuchability',
      line1: 'So much',
      line2: 'ability',
      subhead:
        'Sport, nutrition and family care programmes — free for our members.',
      cta: 'See what they can do',
      sessionsWord: 'sessions',
    },
    stats: {
      title: 'Impact you can count',
      updated: 'Annual Report 2024/25',
      items: [
        { id: 'sessions', value: 6859, suffix: '', label: 'sessions offered' },
        { id: 'families', value: 490, suffix: '', label: 'families supported' },
        { id: 'activityTypes', value: 84, suffix: '', label: 'activity types' },
        { id: 'volunteerHours', value: 1000, suffix: '+', label: 'volunteer hours / month' },
      ],
    },
    activities: {
      title: 'Coming up',
      subhead: 'Join an activity, or come along to cheer.',
      recruiting: 'Volunteers welcome',
      joinCta: 'Join as a volunteer',
      viewCta: 'View activity',
    },
    achievements: {
      eyebrow: 'Achievements & impact',
      title: 'What the community has built',
      subhead: 'Collective milestones — no single name attached, because they belong to everyone.',
    },
    corporateImpact: {
      title: 'Companies who show up',
      subhead: 'Real teams, real shifts, real impact.',
      wallLabel: 'With thanks to',
      wallSubhead: 'Corporates, law firms and foundations who’ve backed Love 21 — named in our 2024–25 annual report.',
      cta: 'Bring your company',
    },
    spotlight: {
      title: 'Ability spotlight',
      subhead: 'Every achievement here is real.',
      reveal: 'Meet',
      readMore: 'Read the story',
    },
    map: {
      kicker: 'Across Hong Kong',
      title: 'Where we gather',
      subhead: 'Our activities run in neighbourhoods all over the city.',
    },
    paths: {
      seekingTitle: 'Looking for support for yourself or your family?',
      seekingBody: 'Membership is free. Tell us a little about you and the team will be in touch.',
      seekingCta: 'Get support',
      title: 'Ready to make a difference?',
      subhead: 'Pick where you want to start.',
      witness: {
        tag: 'Witness',
        title: 'See the community',
        body: 'Meet the people and the moments that show what ability looks like.',
        cta: 'Explore Community',
      },
      take: {
        tag: 'Take part',
        title: 'Volunteer with us',
        body: 'Bring your time and skills to an activity that fits you.',
        cta: 'Start volunteering',
      },
      support: {
        tag: 'Support',
        title: 'Give with meaning',
        body: 'Your gift funds real activities you can see on this page.',
        cta: 'Give today',
      },
    },
    footer: {
      contact: 'Contact us',
      contactSpace: 'Love 21 Space',
      contactOffice: 'Office (post)',
      contactEnquiries: 'General enquiries',
      contactPartnerships: 'Partnerships',
      tax: 'Love 21 Foundation is a registered charity in Hong Kong. Donations of HK$100 or more are tax-deductible under Section 88.',
      portal: 'Member portal',
      support: 'Get support',
      followUs: 'Follow us',
      rights: 'All rights reserved.',
      explore: 'Explore',
      more: 'More',
      aboutLove21: 'About Love 21 ↗',
      annualReport: 'Annual Report ↗',
    },
    community: {
      eyebrow: 'Community · proof & learning',
      title: 'Ability, already large.',
      subhead:
        'Real moments from our members — and the facts that show why this work matters. There is no separate Learn page; the community is the classroom.',
      filterAll: 'All',
      filters: {
        sport: 'Sport',
        art: 'Art / Music / Dance',
        nutrition: 'Nutrition',
        family: 'Family',
        fitness: 'Fitness',
        special: 'Special Events',
        outings: 'Outings',
        csr: 'CSR',
      },
      shareCta: 'Share a moment',
      shareTitle: 'Share a moment',
      shareHint: 'Share a real moment in your own words — a short paragraph is enough.',
      shareAsLabel: 'Posting as',
      shareAuthorLabel: 'Your name',
      shareAuthorPlaceholder: 'e.g. Alex Chan',
      shareEmailLabel: 'Email (optional)',
      shareEmailPlaceholder: 'So we can tell you when it goes live',
      shareEmailInvalid: 'Please enter a valid email, or leave it blank.',
      sharePhoto: 'Photo',
      sharePhotoAdd: 'Add a photo',
      sharePhotoAttached: 'Photo attached',
      sharePhotoRemove: 'Remove photo',
      sharePhotoUploading: 'Uploading photo…',
      sharePhotoTooLarge: 'That image is larger than 5MB — please choose a smaller one.',
      sharePhotoWrongType: 'Please choose a JPEG, PNG or WebP image.',
      sharePhotoFailed: 'The photo could not be uploaded — please try again.',
      shareLine: 'Your story',
      shareLinePlaceholder: 'e.g. Finished the race with the whole crew, high-fives all round.',
      shareLengthHint: 'At least {min} characters — {n} so far',
      shareActivityLabel: 'What was it about?',
      shareActivityHint: 'This is the tag on your card, and the tab it appears under.',
      shareRelationshipLabel: 'Your relationship to Love 21',
      relationships: {
        volunteer: 'Volunteer',
        parent: 'Parent or family member',
        supporter: 'Supporter',
      },
      shareConsent: 'I have permission to share this photo and story publicly.',
      shareReviewNote: 'Posts require review before going public.',
      shareSubmit: 'Submit for review',
      shareClose: 'Close',
      shareSent: 'Submitted for review — thank you.',
      shareError: 'Something went wrong — please try again.',
      knowledgeHook: 'Want to try one with them? → Volunteer',
      dotsCaption: '700 babies · 1 lit',
      sliderGuess: 'Drag to guess how many',
      sliderReveal: 'Reveal the real number',
      sliderYourGuess: 'Your guess',
      sliderReal: 'The real number',
      sliderUnit: 'activities',
      emptyFilter: 'No moments in this program yet — try another filter.',
      momentsLabel: 'moments of ability and counting',
      celebrateCta: 'Celebrate',
      instagramLabel: 'From Instagram',
      instagramTag: 'Instagram',
      instagramCta: 'View on Instagram',
      pagePrev: 'Previous',
      pageNext: 'Next',
      showingRange: 'Showing {from}–{to} of {total} moments',
      photoAlt: 'Love 21 members taking part in an activity',
      imageLabel: 'Photo',
      timeToday: 'Today',
      timeDayAgo: '{n} day ago',
      timeDaysAgo: '{n} days ago',
      timeWeekAgo: '{n} week ago',
      timeWeeksAgo: '{n} weeks ago',
      timeMonthAgo: '{n} month ago',
      timeMonthsAgo: '{n} months ago',
      stayClose: {
        eyebrow: 'Stay close',
        title: 'Want to create more stories?',
        body: 'Receive Love 21 news in your inbox, or discover the many ways to be part of our community.',
        emailLabel: 'Email address',
        emailPlaceholder: 'Email address',
        subscribe: 'Subscribe',
        subscribed: 'Thanks — we will be in touch when the mailing list goes live.',
        volunteer: 'Volunteer',
        donate: 'Donate',
        partner: 'Partner',
      },
    },
    mediaNews: {
      eyebrow: 'Longer reads',
      title: 'Want more stories?',
      subhead: 'Longer articles and press coverage live on our articles page.',
      cta: 'Browse articles',
      readMore: 'Read more',
      prevSlide: 'Previous story',
      nextSlide: 'Next story',
      pause: 'Pause slideshow',
      play: 'Play slideshow',
      slideLabel: 'Story {n} of {total}',
    },
    articlesPage: {
      eyebrow: 'Media & press',
      title: 'Articles',
      subhead: 'Longer stories and press coverage of Love 21 — from newsrooms and our community.',
      ourStories: 'From Love 21',
      ourStoriesLede: 'Written by the foundation — read them here.',
      readArticle: 'Read article',
      backToCommunity: 'Back to community',
    },
    volunteer: {
      kicker: 'Take part',
      title: 'Show up. Meet them.',
      subhead:
        'Stigma shrinks face to face. Pick a session, bring your energy, and take part — not from the sidelines.',
      communityLink: 'See the community first',
      teachingNote:
        "If you'd like to commit to teaching your own weekly class for our beneficiaries or supporting an already existing class, please contact our Programme Manager Kenneth at",
      teachingEmail: 'maggie@love21foundation.com',
      teachingKicker: 'Teaching volunteers',
      modeTitle: 'How do you want to take part?',
      individualTag: 'Individual',
      individualTitle: 'Book or assist a class',
      individualBody: 'Join one session as an active participant. HandsOn listings and Love 21 sessions, in one place.',
      individualCta: 'Browse sessions',
      corporateTag: 'Corporate',
      corporateTitle: 'CSR sessions + giving',
      corporateBody: 'Group volunteering — drumming, Zumba, cooking, art. Contact us; we plan together.',
      corporateCta: 'Contact for CSR',
      skillsTitle: 'What can you bring?',
      skillsHint: 'Optional — tap to filter.',
      skills: {
        patient: 'Patient',
        sports: 'Sports',
        music: 'Music',
        kitchen: 'Kitchen',
        photography: 'Photography',
        youth14: 'Youth 14+',
        cantonese: 'Cantonese optional',
      },
      clearSkills: 'Clear filters',
      filterMySkills: 'Filter by my skills',
      filterMySkillsHint: 'Show sessions that match skills saved on your profile.',
      filterMySkillsEmpty: 'Add skills on My Impact first, then filter the list here.',
      filterMySkillsEdit: 'Edit my skills',
      filterMySkillsLogin: 'Log in to filter by your saved skills',
      listTitle: 'Open sessions',
      emptyList: 'No sessions match those skills — try clearing a filter.',
      emptyListNoSessions:
        'No open sessions right now. Check back soon, or ask Love 21 about upcoming classes.',
      loadError:
        'Could not load sessions from the server. Check that the API is running, then refresh.',
      recruiting: 'Recruiting',
      fullBadge: 'Full',
      spots: '{filled}/{capacity} spots',
      sourceLove21: 'Love 21',
      sourceHandson: 'HandsOn',
      viewDetail: 'View session',
      backToHub: 'All sessions',
      detailWhat: 'What you’ll actually do',
      detailEligibility: 'Who can join',
      detailSafeguard:
        'Safeguarding: coaches are on site. We may ask for a brief introduction before your first session — we are still finalising the full process with Love 21.',
      handsonCapacity:
        'HandsOn: {filled}/{capacity} booked · {interested} interested here',
      registerInterest: 'Register interest',
      completeHandson: 'Also book on HandsOn (optional)',
      joinSession: 'Join session',
      formIntro:
        'Love 21 is looking for passionate volunteers to join sports, nutrition and holistic programmes for our Down syndrome, autistic and neurodiverse community.',
      interestFormIntroLoggedIn:
        'You’re signed in — we’ll use your saved volunteer details. Confirm the safeguard note to register interest.',
      shortFormIntro:
        'Quick signup — you’re confirmed for this session if a spot is open. No staff wait.',
      shortFormIntroLoggedIn:
        'You’re signed in — confirm age and the safeguard note to take this spot.',
      joiningAs: 'Joining as {name} · {email}',
      joiningAsEdit: 'Update profile',
      shortName: 'Full name',
      shortSubmit: 'Confirm my spot',
      safeguardAck:
        'I understand I will be an active helper, coaches are on site, and I will follow the class briefing (including emergency steps).',
      emergencyName: 'Emergency contact name',
      emergencyPhone: 'Emergency contact phone',
      fullError: 'This session is full — try another class.',
      signupError: 'We could not save your signup. Please try again.',
      signupDuplicate: 'You’re already signed up for this session.',
      interestChineseName: 'Chinese full name',
      interestEnglishName: 'English full name',
      interestAgeGroup: 'Age / demographic',
      ageGroups: {
        youth14_18: 'Youth volunteer (14–18)',
        age19_29: '19–29',
        age30_44: '30–44',
        age45_59: '45–59',
        age60_plus: '60+',
      },
      ageGroupHint: 'Helps Love 21 understand who is volunteering — not used for marketing.',
      interestGender: 'Gender',
      genders: {
        female: 'Female',
        male: 'Male',
        prefer_not: 'Prefer not to say',
      },
      interestEmail: 'Email',
      interestPhone: 'Contact number',
      interestRoles: 'Which role would you like to apply for? (select all that apply)',
      roles: {
        assistant: "I'd like to be an assistant of an existing class",
        host: "I'd like to host / lead a new class for members",
        event: "I'd like to support as an event helper",
        other: 'Other',
      },
      interestRoleOther: 'Please specify other role',
      interestAbout: 'Tell us a little more about yourself (interests & skills)',
      interestDiscovery: 'How did you learn about our volunteer programme?',
      discovery: {
        existing: 'Existing Love 21 volunteer',
        social: "Love 21's social media",
        edm: "Love 21's eDM / email",
        company: 'Company',
        other: 'Other',
      },
      interestDiscoveryOther: 'Please specify',
      interestSubmit: 'Submit volunteer signup',
      interestCancel: 'Cancel',
      interestDuplicate: 'You already registered interest for this session.',
      interestError: 'Could not save your interest. Check the API is running, then try again.',
      hubSignupTitle: 'Sign up as a Love 21 volunteer',
      hubSignupSubhead: 'Pick a session above for the shortest path — or use the full interest form here.',
      hubSignupCta: 'Open signup form',
      hubCreateAccountCta: 'Create an account instead',
      hubSignedInTitle: 'You’re signed in',
      hubSignedInSubhead:
        'Pick a class above to join with your saved details. Update your volunteer profile anytime on My Impact.',
      hubSignedInCta: 'My volunteer profile',
      joinConfirmTitle: 'Join this session?',
      joinConfirmBody: 'We’ll hold your spot and open your class briefing.',
      joinConfirmYes: 'Yes, I’m in',
      joinConfirmNo: 'Not yet',
      successTitle: 'You’re down for {session}.',
      successBody:
        'Your spot is confirmed. Open the short briefing before you go — then support a class with a gift if you like.',
      successGiveCta: 'Support with a gift',
      successHome: 'Back to home',
      successBriefingCta: 'Open class briefing',
      successSaveCta: 'Save sessions to My Impact',
      briefingKicker: 'Before you go',
      briefingTitle: 'Your class briefing',
      briefingArrive: 'Arrive by',
      briefingMeet: 'Meeting point',
      briefingWear: 'What to wear / bring',
      briefingDo: 'What you’ll do',
      briefingEmergency: 'Emergencies',
      briefingCancel: 'If you cannot come',
      corporatePanelTitle: 'Corporate volunteering',
      corporateBullets: [
        'African drumming workshops',
        'Zumba fitness sessions',
        'Healthy cooking classes',
        'Arts and crafts with members',
      ],
      corporateFormTitle: 'Tell us about your team',
      corporateOrg: 'Organisation',
      corporateContact: 'Contact name',
      corporateEmail: 'Work email',
      corporateMessage: 'What are you hoping to do?',
      corporateSubmit: 'Send enquiry',
      corporateThanks: 'Thanks — we’ll reply by email.',
      changeMode: 'Choose a different path',
    },
    give: {
      kicker: 'Support',
      title: 'Give with meaning',
      subhead: 'Money, things, or a campaign friends can join — your gift keeps programmes free for members.',
      tabMoney: 'Money',
      tabWishlist: 'Wishlist',
      tabFundraise: 'Fundraise',
      amountLabel: 'Your gift (HKD)',
      customAmountLabel: 'Or enter any amount',
      customAmountHint: 'Every dollar counts — type any amount from HK$1.',
      everyDollarCounts: 'Every dollar counts!',
      impactLabel: 'What this becomes',
      impactSmall: 'Every dollar helps keep programmes free for members.',
      once: 'Once',
      weekly: 'Weekly',
      monthly: 'Monthly',
      programmeLabel: 'Optional programme',
      receiptNote:
        'For donations of HK$100 or above, an official receipt can be issued and mailed on request. Contact Maggie at Maggie@love21foundation.com.',
      otherMeansTitle: 'Donate by other means',
      otherMeansBank: 'HSBC transfer: 582-350526-838 · FPS ID: 164778151',
      otherMeansCheque: 'Cheques payable to "Love 21 Foundation Limited".',
      otherMeansAddress:
        'Mail to: 1102, 11/F, Artisan Lab, 21 Luk Hop Street, San Po Kong, Kowloon, HK.',
      programmes: {
        sports: 'Sports',
        fitness: 'Fitness',
        nutrition: 'Nutrition',
        family: 'Family',
        where_needed: 'Where needed most',
      },
      section88: 'Donations of HK$100 or more are tax-deductible under Section 88.',
      trustStrip: '~86% of funds go to programmes (Annual Report).',
      emailLabel: 'Email for updates',
      emailHint: 'Needed if you opt in to gift-journey updates (stands in for Stripe checkout email).',
      emailRequiredJourney: 'Add an email to opt in to journey updates.',
      receiptTitle: 'Official receipt (Section 88)',
      receiptUseAccount: 'Use my account details for the receipt',
      receiptUseAccountHint: 'We’ll email the receipt to your login address.',
      receiptNameLabel: 'Full name on receipt',
      receiptEmailLabel: 'Email for receipt',
      receiptEmailHint: 'We’ll send the official receipt here. Same address can get gift-journey updates if you opt in.',
      receiptForOther: 'Issue the receipt in someone else’s name',
      receiptForOtherHint:
        'For a different taxpayer (e.g. a partner or company). The name on the receipt should match who claims the deduction.',
      receiptRequired: 'Add the name and email for the official receipt.',
      applyCustom: 'Apply',
      journeyOptInLabel: 'Email me as this gift goes through',
      journeyOptInHelper:
        'Received → matched to programmes → when a session happens. Gift-use updates only — not a newsletter.',
      journeyTitle: 'Where your gift is going',
      journeyReceived: 'Received',
      journeyMatched: 'Matched to programmes',
      journeySession: 'Session update',
      journeyEmailNote: 'When there’s news, we’ll email {email}.',
      journeyAdvance: 'See next update',
      donateCta: 'Donate',
      donateWorking: 'Working…',
      wishlistTitle: 'Wishlist',
      wishlistSubhead: 'Pledge items our programmes need — we’ll email how to send or drop off.',
      needed: 'Needed {n}',
      pledged: 'Pledged {n}',
      pledgeCta: 'Pledge',
      pledgeTitle: 'Pledge this item',
      pledgeQty: 'Quantity',
      pledgeNote: 'Note (optional)',
      pledgeSubmit: 'Send pledge',
      pledgeSuccess: 'We’ll email how to send or drop off.',
      pledgeClose: 'Close',
      wishlistEmpty: 'Nothing on the wishlist right now.',
      fundraiseTitle: 'Create a fundraiser',
      fundraiseSubhead: 'Three steps: create, wait for approval, then share and watch progress.',
      fundraiseSteps: [
        'Create your page',
        'We review (approval)',
        'Share & see progress',
      ],
      createCampaignCta: 'Start a campaign',
      liveCampaigns: 'Live campaigns',
      noLiveCampaigns: 'No approved fundraisers yet.',
      yourCampaigns: 'Your campaigns',
      noCampaigns: 'No campaigns yet — create one above.',
      formTitle: 'Campaign title',
      formStory: 'Your story',
      formGoal: 'Goal (HKD)',
      formCover: 'Cover image',
      formEnd: 'End date',
      formSubmit: 'Submit for approval',
      formWorking: 'Submitting…',
      formError: 'Couldn’t create the campaign. Please try again.',
      campaignProgress: 'HK${raised} of HK${goal}',
      campaignShare: 'Copy link',
      campaignShareDone: 'Link copied',
      campaignDonate: 'Donate to this campaign',
      campaignPending: 'Pending approval',
      campaignApproved: 'Approved',
      campaignRejected: 'Rejected',
      campaignNotFound: 'We couldn’t find that campaign.',
      campaignAwaitingApproval:
        'This fundraiser is waiting for Love 21 approval before donations open.',
      stickyDonate: 'Donate',
      thanksAck: 'Thank you. Your gift helps keep programmes free for members.',
      thanksNotifyLabel: 'Email me when there’s news on how this gift was used.',
      thanksNotifyHelper:
        'Only when something real happened — e.g. a session ran. No newsletter spam.',
      thanksEmail: 'Email',
      thanksNotifyToast: 'You’ll get updates at {email}',
      thanksSampleUpdate:
        'Sample update: “Your gift helped make Saturday’s dance class possible.”',
      thanksCreateAccount: 'Want gifts and volunteer hours in one place?',
      thanksCreateAccountBody:
        'Create a free account with this email — we’ll attach this gift automatically.',
      thanksCreateCta: 'Create account',
      thanksNoThanks: 'No thanks — email updates are enough',
      thanksExistingBody: 'We found an account for this email — this gift is on it.',
      thanksViewGiving: 'View your giving',
      thanksVolunteer: 'Volunteer',
      thanksShareCampaign: 'Share a campaign',
      thanksHome: 'Home',
      thanksSaveImpact: 'Save my gifts to My Impact',
    },
    login: {
      kicker: 'Welcome back',
      signInTitle: 'Log In',
      signUpTitle: 'Create an account',
      subhead:
        'See your volunteer sessions and gifts in one place. Donating never requires an account.',
      modeLabel: 'Account mode',
      signInTab: 'Log In',
      signUpTab: 'Sign up',
      fullName: 'English full name',
      chineseName: 'Chinese full name',
      phone: 'Contact number',
      volunteerProfileHint:
        'We save this on your volunteer profile so class signups stay short.',
      email: 'Email',
      password: 'Password',
      signInCta: 'Log In',
      signUpCta: 'Create account',
      working: 'Working…',
      genericError: 'Something went wrong. Try again.',
      notConfigured: 'Supabase Auth is not configured in this environment.',
      checkEmail:
        'Account created. Confirm the email link from Supabase, then log in. (For demo: Authentication → Providers → Email → disable Confirm email.)',
      memberHandoffNote:
        'Not a volunteer or donor? Looking for class schedules or Love 21 family events?',
      memberHandoffCta: 'Go to the Love 21 family portal →',
      backToMe: 'Back to My Impact',
    },
    me: {
      kicker: 'What your support became',
      title: 'My Impact',
      subhead:
        'One place for your combined story — then open Volunteering or Giving for the detail. This is a supporter page, not a member app.',
      tabImpact: 'Overview',
      tabVolunteer: 'Volunteering',
      tabGiving: 'Giving',
      tabAccount: 'Account',
      overviewLead:
        'Learning, hours and gifts grow one garden. Session proofs land here when what you funded actually runs.',
      loading: 'Loading your impact…',
      gateTitle: 'Log In to see your impact',
      gateBody:
        'Create a free account to keep gifts, hours and proof receipts in one place. You can still donate without logging in.',
      gateCta: 'Log In',
      hello: 'Signed in as',
      logOut: 'Log out',
      gardenKicker: 'Combined story',
      gardenTitle: 'Learn, show up, give — grown together',
      gardenBody:
        'This tree grows through your story — stories you read, hours you give, money and wishlist pledges. Volunteering and Giving hold the session and gift lists.',
      gardenGiven: 'Given',
      gardenGifts: 'Gifts',
      gardenClasses: 'Classes funded',
      gardenHours: 'Volunteer hours',
      gardenLearn: 'Stories read',
      gardenItems: 'Items pledged',
      gardenPillarHint: 'Growth order: learn → volunteer → give (money & wishlist items).',
      gardenLearnCta: 'Learn on News →',
      gardenVolunteerCta: 'Find a session →',
      gardenGiveCta: 'Give money →',
      gardenItemsCta: 'Pledge an item →',
      receiptsKicker: 'Proof receipts',
      receiptsTitle: 'When what you funded actually happened',
      receiptsBody:
        'Not a gift list — a note when a session your support helped keep free actually ran. Counts only; never a named member.',
      receiptsEmpty:
        'No proof receipts yet. When a session your gift helped keep free runs, it will show up here.',
      receiptsDeidentified: 'De-identified · no names shared',
      conversionKicker: 'A natural next step',
      conversionMonthlyTitle: 'Become a monthly giver?',
      conversionMonthlyBody:
        'A steady gift keeps the next fortnight of classes free — no calculator, just continuity.',
      conversionMonthlyCta: 'Give monthly',
      conversionHoursTitle: 'You’ve given {hours} hours — become a monthly giver?',
      conversionHoursBody:
        'You’ve already shown up. A monthly gift keeps programmes free for members between sessions.',
      conversionTermTitle: 'One more class funds a whole term',
      conversionTermBody:
        'You’re about HK${toward} toward a HK${cost} class fund. One more gift can finish the set.',
      conversionTermCta: 'Fund a class',
      conversionFirstTitle: 'Turn hours into lasting support',
      conversionFirstBody:
        'You’ve given {hours} hours on site. A first gift helps keep the next class free for members.',
      conversionFirstCta: 'Make a gift',
      accountKicker: 'Account & consent',
      accountTitle: 'How we stay in touch',
      accountBody:
        'Profile, language, journey updates and consent — change these anytime.',
      accountProfile: 'Profile',
      accountEmail: 'Email',
      accountName: 'Name',
      accountLanguage: 'Language',
      accountLanguageHint: 'Applies across the site on this device.',
      accountNotifications: 'Notifications',
      accountNotificationsHint:
        'Journey notes when a funded session runs — not a newsletter blast.',
      accountJourneyOptIn: 'Gift-use updates',
      accountJourneyOptInHint: 'Tell me when a session my gift helped keep free actually happens.',
      accountEmailOptIn: 'Email reminders',
      accountEmailOptInHint: 'Occasional notes about sessions and recognition — never spam.',
      accountConsent: 'Consent',
      accountConsentHint:
        'We never name members in proof receipts. Photo consent is separate and optional.',
      accountPhotoConsent: 'I may appear in supporter stories (optional)',
      accountPhotoConsentHint:
        'Only if you volunteer on camera and staff clear the photo. You can withdraw anytime.',
      accountSaved: 'Preferences saved',
      volunteerKicker: 'Volunteer profile',
      volunteerTitle: 'Your volunteering',
      volunteerEmpty:
        'No sessions yet. Sign up for a class and your hours and recognition will show up here.',
      volunteerCta: 'Find a session',
      volunteerMoreCta: 'Join another session',
      volunteerHoursNote:
        'Hours here come from Love 21 session signups on this site — not HandsOn bookings.',
      skillsTitle: 'Your skills',
      skillsHint:
        'Saved to your profile. On Volunteer, turn on “Filter by my skills” to match open sessions.',
      skillsSave: 'Save skills',
      skillsSaved: 'Skills saved',
      skillsNeedEmail: 'Sign in with an email to save skills permanently.',
      statSessions: 'Sessions',
      statHours: 'Hours',
      statProgrammes: 'Programmes',
      sessionsTitle: 'Your sessions',
      interestsTitle: 'Your interests',
      interestsLead:
        'HandsOn leads you registered here — still finish booking on HandsOn if the listing is external.',
      interestRegistered: 'Interest registered',
      sessionConfirmed: 'Confirmed',
      sessionAttended: 'Attended',
      sessionNoShow: 'No show',
      sessionApplied: 'Applied',
      openBriefing: 'Class briefing',
      feedbackTitle: 'How was this session?',
      feedbackLead: 'Optional — helps Love 21 improve the next one.',
      feedbackRating: 'Overall experience (1–5)',
      feedbackWouldReturn: 'Would you volunteer with us again?',
      feedbackWouldReturnYes: 'Yes',
      feedbackWouldReturnNo: 'No',
      feedbackNote: 'Anything we could improve? (optional)',
      feedbackNotePlaceholder: 'A short note is enough',
      feedbackSubmit: 'Send feedback',
      feedbackSubmitting: 'Sending…',
      feedbackThanks: 'Thanks for your feedback',
      feedbackError: 'Could not save — add at least one answer, or try again.',
      badgesTitle: 'Recognition',
      badgesSubhead:
        'Recognition for showing up — useful for CVs and CSR, not a points game.',
      badgeEarned: 'Earned',
      badgeLocked: 'Next',
      giveCta: 'Give',
      givingTitle: 'Your giving',
      givingSubhead:
        'Each gift’s journey — received, rooted, session grown. Overview shows learning, hours and gifts grown together.',
      givingEmpty: 'No gifts yet. Every dollar helps keep programmes free for members.',
      viewGift: 'View gift',
      journeyReceived: 'Gift received',
      journeyMatched: 'Rooted in a programme',
      journeySession: 'A session grew',
      journeyStatusDone: 'Done',
      journeyStatusProcessing: 'Still growing',
      journeyStatusWaiting: 'Not yet',
      journeyGrowthLabel: 'Growth {n} of 3',
      journeyGrowthCumulativeTitle: 'Your impact growth',
      journeyGrowthCumulativeBody:
        'All your gifts grow one tree — from a first gift through matched funds to sessions that ran, helping members realise their abilities through sport, nutrition and care.',
      journeyGrowthCumulativeLabel: 'Cumulative growth {n} of 4',
      journeyGrowthTotalGiven: 'Given',
      journeyGrowthGiftCount: 'Gifts',
      journeyGrowthSessions: 'Sessions',
      journeyDetailReceivedDone:
        'Love 21 has recorded your gift. It sits ready to be allocated into programme funds.',
      journeyDetailReceivedProcessing:
        'Confirming the payment landed — usually within a day of checkout.',
      journeyDetailReceivedWaiting: 'Waiting for the gift to be recorded.',
      journeyDetailMatchedDone:
        'Allocated into the {programme} programme fund — coaches, venue and materials so members can attend free.',
      journeyDetailMatchedProcessing:
        'Staff are placing this gift into the {programme} fund this fortnight (about 80–86% of gifts go straight to programmes).',
      journeyDetailMatchedWaiting:
        'Once received, this gift will be rooted into {programme} — not a general newsletter opt-in.',
      journeyDetailSessionDone:
        'A {programme} session ran for members. Your gift helped keep that day free for the community.',
      journeyDetailSessionDoneNamed:
        '{title} ran on {when}. Your gift helped keep that session free for members.',
      journeyDetailSessionProcessing:
        'Waiting for the next {programme} session on the calendar — you’ll get a gift-use note when it runs, not a newsletter.',
      journeyDetailSessionWaiting:
        'After matching, you’ll hear when a {programme} session that this gift supported actually runs.',
    },
    support: {
      eyebrow: 'Support',
      title: 'Looking for support for your family?',
      intro:
        'Love 21 runs sport, nutrition and family programmes for the Down syndrome, autistic and neurodiverse community in Hong Kong. If you think we could be a good fit, we would love to meet you.',
      processTitle: 'Tell us about your family',
      processBody:
        'Fill in a short form and our team will contact you as soon as possible to talk through what your family needs.',
      formCta: 'Fill in the form',
      emailNote: 'Prefer email? Write to info@love21foundation.com',
      memberNote: 'Already a Love 21 family?',
      memberCta: 'Sign in to see your classes',
      backHome: 'Back to home',
    },
    admin: {
      kicker: 'Staff',
      hubTitle: 'Staff hub',
      accessDenied: 'Access denied',
      accessDeniedBody:
        'This area needs an admin account. Sign in with a staff login, or ask a teammate to set your profiles.role to admin.',
      signedInAs: 'Signed in as {email} · role from API: {role}',
      signOutRetry: 'Sign out and try again',
      backHome: '← Home',
      verifyError: 'Could not verify admin role.',
      navOverview: 'Overview',
      navOverviewHint: 'Metrics and today’s queue',
      navArticles: 'Articles',
      navArticlesHint: 'Write and publish news',
      navStories: 'Story desk',
      navStoriesHint: 'Approve photos and copy captions',
      navCampaigns: 'Fundraisers',
      navCampaignsHint: 'Approve community campaigns',
      navAttendance: 'Class roll',
      navAttendanceHint: 'Mark who showed up',
      navModeration: 'Voices review',
      navModerationHint: 'Review supporter stories',
      storiesTitle: 'Story desk',
      storiesIntro:
        'Approve a session photo for public use, then copy the draft captions into Instagram or Facebook. One Approve creates caption drafts. Faces without consent stay blurred — this site never posts to Meta.',
      storiesMetaNote:
        'Copy caption / open Instagram — publishing happens in the Instagram or Facebook apps.',
      storiesLoadError: 'Could not load the story desk.',
      storiesApproveError: 'Approve failed.',
      storiesApproved: 'Approved — caption drafts are ready below.',
      storiesCopied: 'Caption copied — paste into Instagram or Facebook yourself.',
      storiesCopyFailed: 'Copy failed — try download instead.',
      storiesReminded: 'Reminder set for {when} — still publish in the apps, not from here.',
      storiesScheduleError: 'Could not schedule reminder.',
      storiesUnavailable:
        'Story desk needs the session_proofs / social_drafts migration applied (20260802_1130). Until then this queue stays empty.',
      storiesApproveHeading: '1 · Approve session photos',
      storiesApproveLead:
        'Only staff can approve. Consent decides whose faces are shown; Approve never publishes faces without clearance.',
      storiesNoPending: 'No photos waiting. When you approve a photo, drafts appear below.',
      storiesBlurActive: 'Auto-blur active',
      storiesMembers: '{visible} visible · {blurred} blurred',
      storiesApproveCta: 'Approve & create drafts',
      storiesFanoutHeading: 'Preview of what Approve creates',
      storiesWebsiteStory: 'Website story',
      storiesCaptionDrafts: 'Caption drafts',
      storiesCaptionsHeading: '2 · Caption drafts for Instagram & Facebook',
      storiesCaptionsLead:
        'Copy or download, then paste in the Instagram or Facebook apps. A reminder time is only a note — this hub never publishes to Meta.',
      storiesOpenInstagram: 'Open @love21foundation on Instagram',
      storiesCopyHashtags: 'Copy suggested hashtags',
      storiesNoDrafts: 'No caption drafts yet — Approve a photo above to generate some.',
      storiesReminder: 'Reminder',
      storiesCopyCaption: 'Copy caption',
      storiesDownload: 'Download .txt',
      storiesRemind: 'Remind me tomorrow',
      consentCleared: 'All faces cleared',
      consentPartial: 'Partial — unconsented faces blurred',
      consentNone: 'No facial consent — all blurred',
      articlesTitle: 'Articles',
      articlesIntro:
        'Create, edit and publish news, education and report pieces. Bodies save as paragraph blocks; bilingual fields use English and Traditional Chinese.',
      articlesNew: 'New article',
      articlesEdit: 'Edit',
      articlesEmpty: 'No articles yet.',
      articlesUnavailable:
        'Articles CMS needs the articles table applied. Run the content migrations in the SQL editor first.',
      articlesLoadError: 'Could not load articles.',
      articlesSaveError: 'Could not save article.',
      articlesTitleRequired: 'English title is required.',
      articlesSaved: 'Article saved.',
      articlesCreated: 'Draft created.',
      articlesPublished: 'Published.',
      articlesUnpublished: 'Returned to draft.',
      articlesSave: 'Save',
      articlesPublish: 'Publish',
      articlesUnpublish: 'Unpublish',
      articlesCancel: 'Cancel',
      articlesFieldCategory: 'Category',
      articlesFieldFeatured: 'Featured on home',
      articlesFieldTitleEn: 'Title (English)',
      articlesFieldTitleZh: 'Title (繁體中文)',
      articlesFieldExcerptEn: 'Excerpt (English)',
      articlesFieldExcerptZh: 'Excerpt (繁體中文)',
      articlesFieldBodyEn: 'Body (English)',
      articlesFieldBodyZh: 'Body (繁體中文)',
      articlesFieldAuthor: 'Author',
      articlesFieldCover: 'Cover image URL',
      articlesBodyHint: 'Blank line between paragraphs. Saves as paragraph blocks.',
      moderationTitle: 'Voices review',
      moderationIntro:
        'Supporter and family stories submitted for the News Voices tab. Approve to publish, or reject to keep them off the site.',
      campaignsTitle: 'Fundraisers',
      campaignsIntro: 'Approve or reject community fundraising campaigns before they go public.',
      attendanceTitle: 'Class roll',
      attendanceIntro: 'Mark volunteer attendance for upcoming sessions.',
      dashboardTitle: 'Overview',
      dashboardIntro: 'Live metrics and what needs attention today.',
      dashboardTileDonations: 'Donations',
      dashboardTileSessions: 'Upcoming sessions',
      dashboardTileInterests: 'Interests',
      dashboardTilePending: 'Pending work',
      dashboardGiftsEmpty: 'No gifts in this window',
      dashboardGiftsHint: '{n} gifts · website channel',
      dashboardSpotsHint: '{n} spots open',
      dashboardInterestsHint: 'HandsOn interest leads — kept separate from session hours',
      dashboardPendingHint: 'Story desk, fundraisers, and Voices',
      dashboardChartMoney: 'Money given',
      dashboardChartMoneyDesc:
        "Website and individual gifts each month for the past six months (HK$). This is not Love 21's full HKD 13.5M income — programme spend remains 86% of expenditure.",
      dashboardChartMoneyUnit: 'HK$ per calendar month',
      dashboardChartMoneyEmpty: 'No gifts in this window',
      dashboardChartHours: 'Volunteer hours logged',
      dashboardChartHoursDesc:
        'Hours from Love 21 sessions marked on this site over the past six months. HandsOn interest leads stay separate and are never added into these totals.',
      dashboardChartHoursUnit: 'Hours per calendar month',
      dashboardChartHoursEmpty: 'No hours logged in this window',
      dashboardQueueTitle: "Today's queue",
      dashboardQueueIntro:
        'Open items from story desk, class roll, fundraisers, Voices, and impact — based on what is waiting right now.',
      dashboardQueueOpen: 'Open',
      dashboardFunnelTitle: 'Interests → signups → gifts',
      dashboardFunnelIntro:
        'Form-side counts from this site — not anonymous visitor analytics',
      dashboardFunnelDropoffs: 'Biggest drops between stages',
      dashboardFunnelSources: 'How people said they found us',
      dashboardFunnelSourcesHint:
        'From volunteer discovery and donor referral form answers — not campaign tracking codes.',
      dashboardFunnelEmpty: 'No interests, signups, or gifts yet.',
      dashboardFunnelSourcesEmpty: 'No discovery or referral answers recorded yet.',
    },
  },
  'zh-Hant': {
    nav: {
      home: '首頁',
      community: '社群',
      about: '關於',
      news: '新聞',
      help: '協助',
      volunteer: '義工',
      give: '捐助',
      donate: '捐款',
      login: '登入',
      myImpact: '我的影響',
      admin: '管理',
      easyRead: '簡易閱讀',
      language: '語言',
      skipToContent: '跳至內容',
      askForHelp: '尋求協助',
      easyReadBanner: '簡易閱讀已開啟——字更大、按鈕更清楚。',
      easyReadTurnOff: '關閉',
    },
    homeSections: {
      navLabel: '頁面章節',
    },
    news: {
      eyebrow: '最新消息',
      title: 'Love 21 最新動態',
      subhead: '公告、專題解說與年度報告。',
      readMore: '閱讀全文',
      readingTime: '閱讀時間 {n} 分鐘',
      backToNews: '返回首頁',
      notFound: '找不到這篇文章。',
      loadFailed: '無法載入這篇文章，請再試一次。',
      categories: {
        news: '消息',
        education: '專題解說',
        report: '報告',
      },
      mythLabel: '迷思',
      factLabel: '事實',
      embedFallback: '在 Instagram 上查看貼文',
    },
    hero: {
      eyebrow: '#Somuchability',
      line1: '無限',
      line2: '能力',
      subhead: '運動、營養與家庭支援計劃——會員免費。',
      cta: '看看他們的能力',
      sessionsWord: '堂課',
    },
    stats: {
      title: '看得見的影響',
      updated: '2024/25 年度報告',
      items: [
        { id: 'sessions', value: 6859, suffix: '', label: '課程總節數' },
        { id: 'families', value: 490, suffix: '', label: '支援家庭' },
        { id: 'activityTypes', value: 84, suffix: '', label: '活動種類' },
        { id: 'volunteerHours', value: 1000, suffix: '+', label: '義工時數 / 月' },
      ],
    },
    activities: {
      title: '即將舉行',
      subhead: '參加活動，或前來打氣。',
      recruiting: '歡迎義工',
      joinCta: '成為義工',
      viewCta: '查看活動',
    },
    achievements: {
      eyebrow: '成就與影響力',
      title: '社群共同創造的成果',
      subhead: '集體的里程碑——不屬於單一個人，因為它屬於每一位。',
    },
    corporateImpact: {
      title: '願意參與的企業',
      subhead: '真實的團隊、真實的當值、真實的影響力。',
      wallLabel: '衷心感謝',
      wallSubhead: '感謝這些企業、律師事務所及基金會的支持——名單載於 2024–25 年報。',
      cta: '讓你的公司加入',
    },
    spotlight: {
      title: '能力聚焦',
      subhead: '這裡每一項成就都是真實的。',
      reveal: '認識',
      readMore: '閱讀故事',
    },
    map: {
      kicker: '遍佈香港',
      title: '我們的聚腳點',
      subhead: '我們的活動遍佈全港各區。',
    },
    paths: {
      seekingTitle: '正在為自己或家人尋找支援？',
      seekingBody: '會籍免費。告訴我們一些關於你的資料，團隊會與你聯絡。',
      seekingCta: '尋求支援',
      title: '準備好帶來改變嗎？',
      subhead: '選擇你想開始的地方。',
      witness: {
        tag: '見證',
        title: '認識社群',
        body: '認識展現能力的人和時刻。',
        cta: '探索社群',
      },
      take: {
        tag: '參與',
        title: '成為義工',
        body: '把你的時間和才能帶到適合你的活動。',
        cta: '開始做義工',
      },
      support: {
        tag: '支持',
        title: '有意義的捐助',
        body: '你的捐款資助你在此頁看到的真實活動。',
        cta: '立即捐助',
      },
    },
    footer: {
      contact: '聯絡我們',
      contactSpace: 'Love 21 活動空間',
      contactOffice: '辦公室（郵寄）',
      contactEnquiries: '一般查詢',
      contactPartnerships: '合作事宜',
      tax: 'Love 21 Foundation 為香港註冊慈善機構。捐款港幣 100 元或以上可根據第 88 條申請扣稅。',
      portal: '會員專區',
      support: '尋求支援',
      followUs: '關注我們',
      rights: '版權所有。',
      explore: '探索',
      more: '更多',
      aboutLove21: '關於 Love 21 ↗',
      annualReport: '年度報告 ↗',
    },
    community: {
      eyebrow: '社群 · 實證與認識',
      title: '能力，早已盛大。',
      subhead:
        '學員的真實時刻——以及說明這份工作為何重要的事實。沒有獨立的「認識」頁；社群本身就是課堂。',
      filterAll: '全部',
      filters: {
        sport: '運動',
        art: '藝術／音樂／舞蹈',
        nutrition: '營養',
        family: '家庭',
        fitness: '體能',
        special: '特別活動',
        outings: '外出',
        csr: '企業社會責任',
      },
      shareCta: '分享一個時刻',
      shareTitle: '分享一個時刻',
      shareHint: '用自己的話分享一個真實時刻——一小段文字就足夠。',
      shareAsLabel: '以此身分發佈',
      shareAuthorLabel: '你的姓名',
      shareAuthorPlaceholder: '例如：陳大文',
      shareEmailLabel: '電郵（可選）',
      shareEmailPlaceholder: '方便我們在公開時通知你',
      shareEmailInvalid: '請輸入有效電郵，或留空。',
      sharePhoto: '照片',
      sharePhotoAdd: '加入照片',
      sharePhotoAttached: '已附上照片',
      sharePhotoRemove: '移除照片',
      sharePhotoUploading: '正在上載照片…',
      sharePhotoTooLarge: '圖片超過 5MB，請選擇較小的檔案。',
      sharePhotoWrongType: '請選擇 JPEG、PNG 或 WebP 圖片。',
      sharePhotoFailed: '照片上載失敗，請再試一次。',
      shareLine: '你的故事',
      shareLinePlaceholder: '例如：與全隊一起完成比賽，互相擊掌慶祝。',
      shareLengthHint: '至少需要 {min} 個字——目前 {n} 個',
      shareActivityLabel: '這是關於甚麼的？',
      shareActivityHint: '這會成為卡片上的標籤，以及它所屬的分頁。',
      shareRelationshipLabel: '你與 Love 21 的關係',
      relationships: {
        volunteer: '義工',
        parent: '家長或家人',
        supporter: '支持者',
      },
      shareConsent: '我已獲得許可，可公開分享這張照片與故事。',
      shareError: '發生錯誤，請再試一次。',
      shareReviewNote: '貼文須經審核才會公開。',
      shareSubmit: '提交審核',
      shareClose: '關閉',
      shareSent: '已提交審核——謝謝。',
      knowledgeHook: '想和他們一起試試？→ 做義工',
      dotsCaption: '700 名嬰兒 · 點亮 1 個',
      sliderGuess: '拖動猜猜有多少',
      sliderReveal: '顯示真實數字',
      sliderYourGuess: '你的猜測',
      sliderReal: '真實數字',
      sliderUnit: '種活動',
      emptyFilter: '此項目暫無時刻——試試其他篩選。',
      momentsLabel: '個能力時刻，持續累積中',
      celebrateCta: '慶祝',
      instagramLabel: '來自 Instagram',
      instagramTag: 'Instagram',
      instagramCta: '在 Instagram 上查看',
      pagePrev: '上一頁',
      pageNext: '下一頁',
      showingRange: '顯示 {total} 則中的第 {from}–{to} 則',
      photoAlt: 'Love 21 學員參與活動的照片',
      imageLabel: '照片',
      timeToday: '今天',
      timeDayAgo: '{n} 天前',
      timeDaysAgo: '{n} 天前',
      timeWeekAgo: '{n} 週前',
      timeWeeksAgo: '{n} 週前',
      timeMonthAgo: '{n} 個月前',
      timeMonthsAgo: '{n} 個月前',
      stayClose: {
        eyebrow: '保持聯繫',
        title: '想創造更多故事嗎？',
        body: '在收件箱中接收 Love 21 最新消息，或探索加入我們社群的不同方式。',
        emailLabel: '電郵地址',
        emailPlaceholder: '電郵地址',
        subscribe: '訂閱',
        subscribed: '謝謝 — 郵件名單上線後我們會再聯絡你。',
        volunteer: '成為義工',
        donate: '捐款',
        partner: '合作',
      },
    },
    mediaNews: {
      eyebrow: '更長的故事',
      title: '想看更多故事？',
      subhead: '更長的文章與媒體報導都在我們的文章頁。',
      cta: '瀏覽文章',
      readMore: '閱讀全文',
      prevSlide: '上一則',
      nextSlide: '下一則',
      pause: '暫停輪播',
      play: '播放輪播',
      slideLabel: '第 {n} 則，共 {total} 則',
    },
    articlesPage: {
      eyebrow: '媒體與新聞',
      title: '文章',
      subhead: 'Love 21 的長篇故事與媒體報導——來自新聞室與我們的社群。',
      ourStories: '來自 Love 21',
      ourStoriesLede: '由基金會撰寫，可在此閱讀。',
      readArticle: '閱讀文章',
      backToCommunity: '返回社群',
    },
    volunteer: {
      kicker: '參與',
      title: '現身。認識他們。',
      subhead: '面對面，偏見才會縮小。選一節課，帶上你的能量——一起參與，不是旁觀。',
      communityLink: '先看看社群',
      teachingNote:
        '如果你希望為我們的受惠者開辦每週課堂，或支援現有課堂，請聯絡我們的計劃經理 Kenneth：',
      teachingEmail: 'maggie@love21foundation.com',
      teachingKicker: '教學義工',
      modeTitle: '你想怎樣參與？',
      individualTag: '個人',
      individualTitle: '報名或協助課堂',
      individualBody: '以參與者身份加入一節課。HandsOn 與 Love 21 課堂，集中在此。',
      individualCta: '瀏覽課堂',
      corporateTag: '企業',
      corporateTitle: '企業義工與捐助',
      corporateBody: '團隊義工——非洲鼓、Zumba、烹飪、藝術。聯絡我們，一起策劃。',
      corporateCta: '企業查詢',
      skillsTitle: '你能帶來什麼？',
      skillsHint: '可選 — 點選篩選。',
      skills: {
        patient: '有耐心',
        sports: '運動',
        music: '音樂',
        kitchen: '廚房',
        photography: '攝影',
        youth14: '青少年 14+',
        cantonese: '粵語（可選）',
      },
      clearSkills: '清除篩選',
      filterMySkills: '按我的技能篩選',
      filterMySkillsHint: '顯示符合你個人檔案已儲存技能的課堂。',
      filterMySkillsEmpty: '請先在「我的影響力」加入技能，再回來篩選。',
      filterMySkillsEdit: '編輯我的技能',
      filterMySkillsLogin: '登入後可按已儲存技能篩選',
      listTitle: '開放課堂',
      emptyList: '沒有符合這些技能的課堂——試試清除篩選。',
      emptyListNoSessions: '目前沒有開放課堂。稍後再看，或向 Love 21 查詢即將舉行的班。',
      loadError: '無法從伺服器載入課堂。請確認 API 正在運行，然後重新整理。',
      recruiting: '招募中',
      fullBadge: '已滿',
      spots: '{filled}/{capacity} 名額',
      sourceLove21: 'Love 21',
      sourceHandson: 'HandsOn',
      viewDetail: '查看課堂',
      backToHub: '所有課堂',
      detailWhat: '你實際會做什麼',
      detailEligibility: '誰可以參加',
      detailSafeguard:
        '保護措施：教練會在場。首次課堂前我們可能請你簡單自我介紹——完整流程仍與 Love 21 敲定中。',
      handsonCapacity:
        'HandsOn：已訂 {filled}/{capacity} · 此處有興趣 {interested} 人',
      registerInterest: '登記興趣',
      completeHandson: '亦可在 HandsOn 報名（可選）',
      joinSession: '加入課堂',
      formIntro:
        'Love 21 為香港註冊慈善機構，致力透過運動、營養及全方位支援計劃，支持唐氏綜合症、自閉症及神經多樣性社群。我們現正尋找充滿熱誠的義工！',
      interestFormIntroLoggedIn:
        '你已登入——我們會使用你已儲存的義工資料。確認安全守則即可登記興趣。',
      shortFormIntro: '快速報名——有位即確認，無需職員審批。',
      shortFormIntroLoggedIn: '你已登入——確認年齡組別及安全守則即可預留名額。',
      joiningAs: '以 {name} · {email} 報名',
      joiningAsEdit: '更新個人資料',
      shortName: '全名',
      shortSubmit: '確認我的名額',
      safeguardAck: '我明白會以主動幫手身份參與，現場有教練，並會跟從課堂簡介（包括緊急步驟）。',
      emergencyName: '緊急聯絡人姓名',
      emergencyPhone: '緊急聯絡人電話',
      fullError: '此課堂已滿——請選其他班。',
      signupError: '未能儲存報名，請再試。',
      signupDuplicate: '你已報名此課堂。',
      interestChineseName: '中文全名',
      interestEnglishName: '英文全名',
      interestAgeGroup: '年齡／人口組別',
      ageGroups: {
        youth14_18: '青年義工（14–18）',
        age19_29: '19–29 歲',
        age30_44: '30–44 歲',
        age45_59: '45–59 歲',
        age60_plus: '60 歲或以上',
      },
      ageGroupHint: '幫助 Love 21 了解義工人口結構——不用作推廣。',
      interestGender: '性別',
      genders: {
        female: '女',
        male: '男',
        prefer_not: '不透露',
      },
      interestEmail: '聯絡電郵',
      interestPhone: '聯絡電話',
      interestRoles: '請問你對哪一個義工角色感興趣？（可選多項）',
      roles: {
        assistant: '我想以助教身份參與現有課堂',
        host: '我想自己帶領一個課堂',
        event: '我想成為大型活動義工',
        other: '其他',
      },
      interestRoleOther: '請註明其他角色',
      interestAbout: '告訴我們你的喜好和專長吧！',
      interestDiscovery: '請問你從什麼渠道知道 Love 21 的義工機會？',
      discovery: {
        existing: '一向有參加 Love 21 義工活動',
        social: '社交媒體',
        edm: '通訊電郵',
        company: '公司',
        other: '其他',
      },
      interestDiscoveryOther: '請註明',
      interestSubmit: '提交義工報名',
      interestCancel: '取消',
      interestDuplicate: '你已對此課堂登記興趣。',
      interestError: '無法儲存你的興趣。請確認 API 正在運行，然後再試。',
      hubSignupTitle: 'Love 21 義工報名',
      hubSignupSubhead: '上方選課堂最快捷——或在此使用完整興趣表格。',
      hubSignupCta: '打開報名表格',
      hubCreateAccountCta: '改為建立帳戶',
      hubSignedInTitle: '你已登入',
      hubSignedInSubhead:
        '在上方選一節課，用你已儲存的資料報名。可隨時在「我的影響力」更新義工檔案。',
      hubSignedInCta: '我的義工檔案',
      joinConfirmTitle: '加入這個課堂？',
      joinConfirmBody: '我們會為你確認名額並開啟課堂簡介。',
      joinConfirmYes: '好，我參加',
      joinConfirmNo: '先不要',
      successTitle: '你已報名「{session}」。',
      successBody: '名額已確認。出發前請打開簡短簡介——如想支持課堂也可捐助。',
      successGiveCta: '以捐助支持',
      successHome: '返回首頁',
      successBriefingCta: '打開課堂簡介',
      successSaveCta: '儲存課堂到「我的影響」',
      briefingKicker: '出發前',
      briefingTitle: '你的課堂簡介',
      briefingArrive: '到達時間',
      briefingMeet: '集合點',
      briefingWear: '穿著／攜帶',
      briefingDo: '你會做什麼',
      briefingEmergency: '緊急情況',
      briefingCancel: '若不能出席',
      corporatePanelTitle: '企業義工',
      corporateBullets: [
        '非洲鼓工作坊',
        'Zumba 健身課',
        '健康烹飪班',
        '與學員一起做手工藝術',
      ],
      corporateFormTitle: '告訴我們你的團隊',
      corporateOrg: '機構名稱',
      corporateContact: '聯絡人',
      corporateEmail: '公司電郵',
      corporateMessage: '你們希望做什麼？',
      corporateSubmit: '送出查詢',
      corporateThanks: '謝謝——我們會以電郵回覆。',
      changeMode: '選擇另一條路',
    },
    give: {
      kicker: '支持',
      title: '有意義的捐助',
      subhead: '金錢、物資，或讓朋友一起參與的籌款——你的捐助讓會員計劃保持免費。',
      tabMoney: '捐款',
      tabWishlist: '心願清單',
      tabFundraise: '籌款',
      amountLabel: '你的捐款（港幣）',
      customAmountLabel: '或輸入任何金額',
      customAmountHint: '每一元都有意義 — 可由港幣 1 元起。',
      everyDollarCounts: '每一元都有意義！',
      impactLabel: '這筆捐款能成為',
      impactSmall: '每一元都幫助會員計劃保持免費。',
      once: '一次過',
      weekly: '每週',
      monthly: '每月',
      programmeLabel: '可選計劃',
      receiptNote:
        '捐款港幣 100 元或以上，可應要求發出正式收據並郵寄。查詢請聯絡 Maggie：Maggie@love21foundation.com。',
      otherMeansTitle: '其他捐款方式',
      otherMeansBank: '匯豐銀行過數：582-350526-838 · FPS ID：164778151',
      otherMeansCheque: '支票抬頭：「Love 21 Foundation Limited」。',
      otherMeansAddress:
        '郵寄地址：香港九龍新蒲崗六合街 21 號 Artisan Lab 11 樓 1102 室。',
      programmes: {
        sports: '運動',
        fitness: '體能',
        nutrition: '營養',
        family: '家庭',
        where_needed: '最需要的地方',
      },
      section88: '港幣 100 元或以上捐款可根據第 88 條申請扣稅。',
      trustStrip: '約 86% 資金用於計劃（年度報告）。',
      emailLabel: '接收更新的電郵',
      emailHint: '若選擇禮物旅程更新則需要（代替 Stripe 結帳電郵）。',
      emailRequiredJourney: '請填寫電郵以選擇旅程更新。',
      receiptTitle: '正式收據（第 88 條）',
      receiptUseAccount: '使用我的帳戶資料開立收據',
      receiptUseAccountHint: '收據會電郵至你的登入電郵。',
      receiptNameLabel: '收據上的全名',
      receiptEmailLabel: '收據電郵',
      receiptEmailHint: '正式收據會寄至此電郵。若選擇旅程更新，也會寄到此地址。',
      receiptForOther: '以他人名義開立收據',
      receiptForOtherHint: '適用於不同納稅人（例如配偶或公司）。收據姓名應與申請扣稅者一致。',
      receiptRequired: '請填寫正式收據所需的姓名與電郵。',
      applyCustom: '套用',
      journeyOptInLabel: '電郵通知我這筆捐款的去向',
      journeyOptInHelper: '已收到 → 配對計劃 → 課堂發生時。只限捐款用途更新，不是通訊。',
      journeyTitle: '你的捐款去向',
      journeyReceived: '已收到',
      journeyMatched: '已配對計劃',
      journeySession: '課堂更新',
      journeyEmailNote: '有消息時會電郵 {email}。',
      journeyAdvance: '查看下一則更新',
      donateCta: '捐款',
      donateWorking: '處理中…',
      wishlistTitle: '心願清單',
      wishlistSubhead: '認捐計劃所需物資——我們會電郵說明如何送交或自取。',
      needed: '需要 {n}',
      pledged: '已認捐 {n}',
      pledgeCta: '認捐',
      pledgeTitle: '認捐此項目',
      pledgeQty: '數量',
      pledgeNote: '備註（可選）',
      pledgeSubmit: '送出認捐',
      pledgeSuccess: '我們會電郵說明如何送交或自取。',
      pledgeClose: '關閉',
      wishlistEmpty: '目前心願清單沒有項目。',
      fundraiseTitle: '發起籌款',
      fundraiseSubhead: '三步：建立、等候審批，然後分享並查看進度。',
      fundraiseSteps: ['建立頁面', '我們審批', '分享並查看進度'],
      createCampaignCta: '開始籌款',
      liveCampaigns: '進行中的籌款',
      noLiveCampaigns: '尚未有已批准的籌款。',
      yourCampaigns: '你的籌款',
      noCampaigns: '尚未有籌款——請在上方建立。',
      formTitle: '籌款標題',
      formStory: '你的故事',
      formGoal: '目標（港幣）',
      formCover: '封面圖片',
      formEnd: '結束日期',
      formSubmit: '提交審批',
      formWorking: '提交中…',
      formError: '無法建立籌款，請再試一次。',
      campaignProgress: '已籌 HK${raised}／目標 HK${goal}',
      campaignShare: '複製連結',
      campaignShareDone: '已複製連結',
      campaignDonate: '捐給此籌款',
      campaignPending: '等候審批',
      campaignApproved: '已批准',
      campaignRejected: '已拒絕',
      campaignNotFound: '找不到此籌款。',
      campaignAwaitingApproval: '此籌款正等候 Love 21 審批，通過後才可接受捐款。',
      stickyDonate: '捐款',
      thanksAck: '謝謝你。你的捐助幫助會員計劃保持免費。',
      thanksNotifyLabel: '有這筆捐款如何被使用的消息時，電郵通知我。',
      thanksNotifyHelper: '只在真實事情發生時——例如一節課舉行了。不會濫發電郵。',
      thanksEmail: '電郵',
      thanksNotifyToast: '你會在 {email} 收到更新',
      thanksSampleUpdate: '示範更新：「你的捐助幫助週六舞蹈班得以舉行。」',
      thanksCreateAccount: '想把捐助與義工時數放在同一處？',
      thanksCreateAccountBody: '用此電郵建立免費帳戶——我們會自動附上這筆捐助。',
      thanksCreateCta: '建立帳戶',
      thanksNoThanks: '不用了——電郵更新已足夠',
      thanksExistingBody: '我們找到此電郵的帳戶——這筆捐助已在帳戶上。',
      thanksViewGiving: '查看你的捐助',
      thanksVolunteer: '做義工',
      thanksShareCampaign: '分享籌款',
      thanksHome: '首頁',
      thanksSaveImpact: '儲存捐助到「我的影響」',
    },
    login: {
      kicker: '歡迎回來',
      signInTitle: '登入',
      signUpTitle: '建立帳戶',
      subhead: '在同一處查看義工課堂與捐助。捐款不必先登入。',
      modeLabel: '帳戶模式',
      signInTab: '登入',
      signUpTab: '註冊',
      fullName: '英文全名',
      chineseName: '中文全名',
      phone: '聯絡電話',
      volunteerProfileHint: '會儲存到義工檔案，之後課堂報名更簡短。',
      email: '電郵',
      password: '密碼',
      signInCta: '登入',
      signUpCta: '建立帳戶',
      working: '處理中…',
      genericError: '出了點問題，請再試一次。',
      notConfigured: '此環境尚未設定 Supabase Auth。',
      checkEmail:
        '帳戶已建立。請先確認 Supabase 電郵連結，然後登入。（演示可在 Authentication → Providers → Email 關閉 Confirm email。）',
      memberHandoffNote:
        '不是義工或捐款人？在找課堂時間表或 Love 21 家庭活動？',
      memberHandoffCta: '前往 Love 21 家庭專區 →',
      backToMe: '返回我的影響',
    },
    me: {
      kicker: '你的支持變成了什麼',
      title: '我的影響',
      subhead:
        '先看合併故事——細節在「義工」與「捐助」。這是支持者頁，不是會員 App。',
      tabImpact: '總覽',
      tabVolunteer: '義工',
      tabGiving: '捐助',
      tabAccount: '帳戶',
      overviewLead:
        '學習、時數與捐助長成同一座花園。你資助的課堂真正舉行時，證明收據會出現在此。',
      loading: '正在載入你的影響…',
      gateTitle: '登入以查看你的影響',
      gateBody: '建立免費帳戶，把捐助、時數與證明收據放在同一處。捐款仍可不登入。',
      gateCta: '登入',
      hello: '已登入',
      logOut: '登出',
      gardenKicker: '合併故事',
      gardenTitle: '學習、現身、捐助——一起成長',
      gardenBody:
        '這棵樹隨你的故事成長——讀過的故事、義工時數、金錢捐助與物資認捐。「義工」與「捐助」頁有詳細列表。',
      gardenGiven: '已捐',
      gardenGifts: '筆數',
      gardenClasses: '資助課堂',
      gardenHours: '義工時數',
      gardenLearn: '已讀故事',
      gardenItems: '已認捐物資',
      gardenPillarHint: '成長順序：學習 → 義工 → 捐助（金錢與物資清單）。',
      gardenLearnCta: '到新聞學習 →',
      gardenVolunteerCta: '尋找課堂 →',
      gardenGiveCta: '金錢捐助 →',
      gardenItemsCta: '認捐物資 →',
      receiptsKicker: '證明收據',
      receiptsTitle: '當你資助的課堂真正舉行',
      receiptsBody: '不是捐助列表——而是你幫助保持免費的課堂真正舉行時的一則通知。只有人數；從不具名。',
      receiptsEmpty: '尚未有證明收據。當你資助的免費課堂舉行時會顯示在此。',
      receiptsDeidentified: '已去識別 · 不分享姓名',
      conversionKicker: '自然下一步',
      conversionMonthlyTitle: '成為每月捐助者？',
      conversionMonthlyBody: '穩定捐助讓下一雙週的課堂保持免費——不是計算器，是延續。',
      conversionMonthlyCta: '每月捐助',
      conversionHoursTitle: '你已付出 {hours} 小時——成為每月捐助者？',
      conversionHoursBody: '你已現身。每月捐助讓課堂之間的計劃保持免費。',
      conversionTermTitle: '再一堂，就湊齊一整期',
      conversionTermBody: '你大約已有港幣 ${toward}，朝向港幣 ${cost} 的課堂基金。再一筆可完成。',
      conversionTermCta: '資助一堂',
      conversionFirstTitle: '把時數化成持續支持',
      conversionFirstBody: '你已在現場付出 {hours} 小時。第一筆捐助幫助下一堂對會員免費。',
      conversionFirstCta: '捐助',
      accountKicker: '帳戶與同意',
      accountTitle: '我們如何聯絡你',
      accountBody: '個人資料、語言、旅程更新與同意——隨時可改。',
      accountProfile: '個人資料',
      accountEmail: '電郵',
      accountName: '姓名',
      accountLanguage: '語言',
      accountLanguageHint: '套用至此裝置上的整個網站。',
      accountNotifications: '通知',
      accountNotificationsHint: '資助課堂舉行時的旅程通知——不是電子報轟炸。',
      accountJourneyOptIn: '捐助用途更新',
      accountJourneyOptInHint: '當我資助的免費課堂實際舉行時通知我。',
      accountEmailOptIn: '電郵提醒',
      accountEmailOptInHint: '偶爾關於課堂與認可的訊息——不會濫發。',
      accountConsent: '同意',
      accountConsentHint: '證明收據從不具名會員。照片同意另行、可選。',
      accountPhotoConsent: '我可出現在支持者故事中（可選）',
      accountPhotoConsentHint: '僅在你鏡頭前義工且職員核實照片時。可隨時撤回。',
      accountSaved: '偏好已儲存',
      volunteerKicker: '義工檔案',
      volunteerTitle: '你的義工服務',
      volunteerEmpty: '尚未有課堂。報名後，時數與認可會顯示在此。',
      volunteerCta: '尋找課堂',
      volunteerMoreCta: '再參加一節',
      volunteerHoursNote: '此處時數來自本站 Love 21 課堂報名——不是 HandsOn 預約。',
      skillsTitle: '你的技能',
      skillsHint: '會儲存到個人檔案。在義工頁可開啟「按我的技能篩選」配對課堂。',
      skillsSave: '儲存技能',
      skillsSaved: '已儲存技能',
      skillsNeedEmail: '請用電郵登入以永久儲存技能。',
      statSessions: '課堂',
      statHours: '時數',
      statProgrammes: '計劃',
      sessionsTitle: '你的課堂',
      interestsTitle: '你的興趣登記',
      interestsLead: '你在此登記的 HandsOn 興趣——若為外部課堂，仍須在 HandsOn 完成報名。',
      interestRegistered: '已登記興趣',
      sessionConfirmed: '已確認',
      sessionAttended: '已出席',
      sessionNoShow: '缺席',
      sessionApplied: '已申請',
      openBriefing: '課堂簡介',
      feedbackTitle: '這次課堂感覺如何？',
      feedbackLead: '可選填——幫助 Love 21 改進下一次。',
      feedbackRating: '整體體驗（1–5）',
      feedbackWouldReturn: '你會再來當義工嗎？',
      feedbackWouldReturnYes: '會',
      feedbackWouldReturnNo: '不會',
      feedbackNote: '有什麼可以改進？（可選）',
      feedbackNotePlaceholder: '簡短留言即可',
      feedbackSubmit: '送出意見',
      feedbackSubmitting: '傳送中…',
      feedbackThanks: '謝謝你的意見',
      feedbackError: '未能儲存——請至少填一項，或稍後再試。',
      badgesTitle: '認可',
      badgesSubhead: '為出席而設——有助履歷與 CSR，不是積分遊戲。',
      badgeEarned: '已獲得',
      badgeLocked: '下一步',
      giveCta: '捐助',
      givingTitle: '你的捐助',
      givingSubhead:
        '每筆捐助的旅程——收到、扎根、課堂成長。總覽是學習、時數與捐助的合併故事。',
      givingEmpty: '尚未有捐助。每一元都幫助會員計劃保持免費。',
      viewGift: '查看捐助',
      journeyReceived: '已收到捐助',
      journeyMatched: '已扎根於計劃',
      journeySession: '課堂已成長',
      journeyStatusDone: '完成',
      journeyStatusProcessing: '仍在成長',
      journeyStatusWaiting: '尚未開始',
      journeyGrowthLabel: '成長 {n}／3',
      journeyGrowthCumulativeTitle: '你的影響成長',
      journeyGrowthCumulativeBody:
        '所有捐助合成一棵樹——從首筆捐助、配對基金到課堂真正舉行，透過運動、營養與關懷，幫助會員發揮自己的能力。',
      journeyGrowthCumulativeLabel: '累積成長 {n}／4',
      journeyGrowthTotalGiven: '已捐',
      journeyGrowthGiftCount: '筆數',
      journeyGrowthSessions: '課堂',
      journeyDetailReceivedDone: 'Love 21 已記錄你的捐助，正待分配至計劃基金。',
      journeyDetailReceivedProcessing: '正在確認付款到帳——通常於結帳後一天內完成。',
      journeyDetailReceivedWaiting: '等候記錄捐助。',
      journeyDetailMatchedDone:
        '已撥入「{programme}」計劃基金——用於教練、場地與物資，讓會員可免費參加。',
      journeyDetailMatchedProcessing:
        '職員正於本雙週把這筆捐助撥入「{programme}」基金（約 80–86% 直接用於計劃）。',
      journeyDetailMatchedWaiting: '收到後會把這筆捐助扎根於「{programme}」——不是一般電子報。',
      journeyDetailSessionDone: '已舉行一節「{programme}」會員課堂。你的捐助有助該日保持免費。',
      journeyDetailSessionDoneNamed: '「{title}」已於 {when} 舉行。你的捐助有助該課堂保持免費。',
      journeyDetailSessionProcessing:
        '等候下一節「{programme}」課堂——舉行時會收到捐助用途通知，不是電子報。',
      journeyDetailSessionWaiting: '配對後，當這筆捐助支持的「{programme}」課堂實際舉行時會通知你。',
    },
    support: {
      eyebrow: '支援',
      title: '想為你的家庭尋找支援？',
      intro:
        'Love 21 在香港為唐氏綜合症、自閉症及其他神經多樣人士提供運動、營養及家庭支援活動。如果你覺得我們可能適合你的家庭，我們很樂意與你見面。',
      processTitle: '告訴我們你的家庭情況',
      processBody:
        '填寫一份簡短表格，我們的團隊會盡快聯絡你，了解你家庭的需要。',
      formCta: '填寫表格',
      emailNote: '想用電郵？請寫信到 info@love21foundation.com',
      memberNote: '已經是 Love 21 家庭？',
      memberCta: '登入查看你的課堂',
      backHome: '返回首頁',
    },
    admin: {
      kicker: '職員',
      hubTitle: '職員中心',
      accessDenied: '無法存取',
      accessDeniedBody:
        '此區需要管理員帳號。請用職員帳號登入，或請同事將你的 profiles.role 設為 admin。',
      signedInAs: '已登入：{email} · API 角色：{role}',
      signOutRetry: '登出後再試',
      backHome: '← 首頁',
      verifyError: '無法核實管理員角色。',
      navOverview: '總覽',
      navOverviewHint: '指標與今日待辦',
      navArticles: '文章',
      navArticlesHint: '撰寫與發佈新聞',
      navStories: '故事台',
      navStoriesHint: '批准相片並複製文案',
      navCampaigns: '籌款',
      navCampaignsHint: '審批社區籌款活動',
      navAttendance: '點名',
      navAttendanceHint: '記錄出席',
      navModeration: '聲音審核',
      navModerationHint: '審核支持者故事',
      storiesTitle: '故事台',
      storiesIntro:
        '批准可公開使用的課堂相片，再把草稿文案複製到 Instagram 或 Facebook。批准會產生文案草稿；未獲同意的面孔會保持模糊——本站不會發佈到 Meta。',
      storiesMetaNote: '複製文案／開啟 Instagram——實際發佈請在 Instagram 或 Facebook App 完成。',
      storiesLoadError: '無法載入故事台。',
      storiesApproveError: '批准失敗。',
      storiesApproved: '已批准——文案草稿在下方。',
      storiesCopied: '已複製文案——請自行貼到 Instagram 或 Facebook。',
      storiesCopyFailed: '複製失敗——可改下載。',
      storiesReminded: '已設定提醒：{when}——仍須在 App 發佈。',
      storiesScheduleError: '無法設定提醒。',
      storiesUnavailable:
        '故事台需要套用 session_proofs／social_drafts 遷移（20260802_1130）。套用前此佇列為空。',
      storiesApproveHeading: '1 · 批准課堂相片',
      storiesApproveLead: '僅職員可批准。同意狀態決定顯示哪些面孔；未獲同意者不會公開。',
      storiesNoPending: '沒有待批相片。批准後草稿會出現在下方。',
      storiesBlurActive: '自動模糊中',
      storiesMembers: '{visible} 可見 · {blurred} 已模糊',
      storiesApproveCta: '批准並建立草稿',
      storiesFanoutHeading: '批准後會產生',
      storiesWebsiteStory: '網站故事',
      storiesCaptionDrafts: '文案草稿',
      storiesCaptionsHeading: '2 · Instagram 與 Facebook 文案草稿',
      storiesCaptionsLead:
        '複製或下載後，在 Instagram 或 Facebook App 貼上。提醒時間只是備註——本中心不會發佈到 Meta。',
      storiesOpenInstagram: '開啟 @love21foundation Instagram',
      storiesCopyHashtags: '複製建議標籤',
      storiesNoDrafts: '尚無文案草稿——請先批准上方相片。',
      storiesReminder: '提醒',
      storiesCopyCaption: '複製文案',
      storiesDownload: '下載 .txt',
      storiesRemind: '明天提醒我',
      consentCleared: '所有面孔已獲同意',
      consentPartial: '部分——未同意面孔已模糊',
      consentNone: '無面孔同意——全部模糊',
      articlesTitle: '文章',
      articlesIntro: '建立、編輯並發佈新聞、教育與報告。正文存成段落區塊；雙語欄位為英文與繁體中文。',
      articlesNew: '新增文章',
      articlesEdit: '編輯',
      articlesEmpty: '尚無文章。',
      articlesUnavailable: '文章管理需要先套用 articles 資料表遷移。',
      articlesLoadError: '無法載入文章。',
      articlesSaveError: '無法儲存文章。',
      articlesTitleRequired: '英文標題為必填。',
      articlesSaved: '已儲存。',
      articlesCreated: '草稿已建立。',
      articlesPublished: '已發佈。',
      articlesUnpublished: '已退回草稿。',
      articlesSave: '儲存',
      articlesPublish: '發佈',
      articlesUnpublish: '取消發佈',
      articlesCancel: '取消',
      articlesFieldCategory: '類別',
      articlesFieldFeatured: '首頁精選',
      articlesFieldTitleEn: '標題（英文）',
      articlesFieldTitleZh: '標題（繁體中文）',
      articlesFieldExcerptEn: '摘要（英文）',
      articlesFieldExcerptZh: '摘要（繁體中文）',
      articlesFieldBodyEn: '正文（英文）',
      articlesFieldBodyZh: '正文（繁體中文）',
      articlesFieldAuthor: '作者',
      articlesFieldCover: '封面圖片網址',
      articlesBodyHint: '段落之間空一行。會存成段落區塊。',
      moderationTitle: '聲音審核',
      moderationIntro: '新聞「聲音」分頁的支持者與家庭故事。批准後公開，拒絕則不上網。',
      campaignsTitle: '籌款',
      campaignsIntro: '審批社區籌款活動，通過後才公開。',
      attendanceTitle: '點名',
      attendanceIntro: '為即將舉行的課堂記錄義工出席。',
      dashboardTitle: '總覽',
      dashboardIntro: '即時指標與今日待辦。',
      dashboardTileDonations: '捐款',
      dashboardTileSessions: '即將舉行的課堂',
      dashboardTileInterests: '興趣登記',
      dashboardTilePending: '待辦',
      dashboardGiftsEmpty: '此期間尚無捐款',
      dashboardGiftsHint: '{n} 筆捐款 · 網站渠道',
      dashboardSpotsHint: '{n} 個空位',
      dashboardInterestsHint: 'HandsOn 興趣登記——與課堂時數分開計算',
      dashboardPendingHint: '故事台、籌款與聲音審核',
      dashboardChartMoney: '捐款金額',
      dashboardChartMoneyDesc:
        '過去六個月網站與個人捐款（港元）。這不是愛二十一全年港幣 1,350 萬收入——計劃開支仍佔支出約 86%。',
      dashboardChartMoneyUnit: '每月港元',
      dashboardChartMoneyEmpty: '此期間尚無捐款',
      dashboardChartHours: '義工時數',
      dashboardChartHoursDesc:
        '過去六個月在本站記錄的愛二十一課堂時數。HandsOn 興趣登記分開顯示，從不合計。',
      dashboardChartHoursUnit: '每月時數',
      dashboardChartHoursEmpty: '此期間尚無時數',
      dashboardQueueTitle: '今日待辦',
      dashboardQueueIntro: '故事台、點名、籌款、聲音與影響數字——依目前等候項目列出。',
      dashboardQueueOpen: '開啟',
      dashboardFunnelTitle: '興趣 → 報名 → 捐款',
      dashboardFunnelIntro: '本站表單累計——不是匿名訪客分析',
      dashboardFunnelDropoffs: '階段之間的最大落差',
      dashboardFunnelSources: '他們如何找到我們',
      dashboardFunnelSourcesHint: '來自義工與捐款表單的自我回報——不是廣告追蹤代碼。',
      dashboardFunnelEmpty: '尚無興趣登記、報名或捐款。',
      dashboardFunnelSourcesEmpty: '尚無來源或轉介答案。',
    },
  },
  'zh-Hans': {
    nav: {
      home: '首页',
      community: '社群',
        about: '关于',
        news: '新闻',
      help: '协助',
      volunteer: '义工',
      give: '捐助',
      donate: '捐款',
      login: '登录',
      myImpact: '我的影响',
      admin: '管理',
      easyRead: '简易阅读',
      language: '语言',
      skipToContent: '跳至内容',
      askForHelp: '寻求协助',
      easyReadBanner: '简易阅读已开启——字更大、按钮更清楚。',
      easyReadTurnOff: '关闭',
    },
    homeSections: {
      navLabel: '页面章节',
    },
    news: {
      eyebrow: '最新消息',
      title: 'Love 21 最新动态',
      subhead: '公告、专题解说与年度报告。',
      readMore: '阅读全文',
      readingTime: '阅读时间 {n} 分钟',
      backToNews: '返回首页',
      notFound: '找不到这篇文章。',
      loadFailed: '无法载入这篇文章，请再试一次。',
      categories: {
        news: '消息',
        education: '专题解说',
        report: '报告',
      },
      mythLabel: '迷思',
      factLabel: '事实',
      embedFallback: '在 Instagram 上查看贴文',
    },
    hero: {
      eyebrow: '#Somuchability',
      line1: '无限',
      line2: '能力',
      subhead: '运动、营养与家庭支援计划——会员免费。',
      cta: '看看他们的能力',
      sessionsWord: '堂课',
    },
    stats: {
      title: '看得见的影响',
      updated: '2024/25 年度报告',
      items: [
        { id: 'sessions', value: 6859, suffix: '', label: '课程总节数' },
        { id: 'families', value: 490, suffix: '', label: '支援家庭' },
        { id: 'activityTypes', value: 84, suffix: '', label: '活动种类' },
        { id: 'volunteerHours', value: 1000, suffix: '+', label: '义工时数 / 月' },
      ],
    },
    activities: {
      title: '即将举行',
      subhead: '参加活动，或前来加油。',
      recruiting: '欢迎义工',
      joinCta: '成为义工',
      viewCta: '查看活动',
    },
    achievements: {
      eyebrow: '成就与影响力',
      title: '社群共同创造的成果',
      subhead: '集体的里程碑——不属于单一个人，因为它属于每一位。',
    },
    corporateImpact: {
      title: '愿意参与的企业',
      subhead: '真实的团队、真实的当值、真实的影响力。',
      wallLabel: '衷心感谢',
      wallSubhead: '感谢这些企业、律师事务所及基金会的支持——名单载于 2024–25 年报。',
      cta: '让你的公司加入',
    },
    spotlight: {
      title: '能力聚焦',
      subhead: '这里每一项成就都是真实的。',
      reveal: '认识',
      readMore: '阅读故事',
    },
    map: {
      kicker: '遍布香港',
      title: '我们的聚脚点',
      subhead: '我们的活动遍布全港各区。',
    },
    paths: {
      seekingTitle: '正在为自己或家人寻找支援？',
      seekingBody: '会籍免费。告诉我们一些关于你的资料，团队会与你联络。',
      seekingCta: '寻求支援',
      title: '准备好带来改变吗？',
      subhead: '选择你想开始的地方。',
      witness: {
        tag: '见证',
        title: '认识社群',
        body: '认识展现能力的人和时刻。',
        cta: '探索社群',
      },
      take: {
        tag: '参与',
        title: '成为义工',
        body: '把你的时间和才能带到适合你的活动。',
        cta: '开始做义工',
      },
      support: {
        tag: '支持',
        title: '有意义的捐助',
        body: '你的捐款资助你在此页看到的真实活动。',
        cta: '立即捐助',
      },
    },
    footer: {
      contact: '联络我们',
      contactSpace: 'Love 21 活动空间',
      contactOffice: '办公室（邮寄）',
      contactEnquiries: '一般查询',
      contactPartnerships: '合作事宜',
      tax: 'Love 21 Foundation 为香港注册慈善机构。捐款港币 100 元或以上可根据第 88 条申请扣税。',
      portal: '会员专区',
      support: '寻求支援',
      followUs: '关注我们',
      rights: '版权所有。',
      explore: '探索',
      more: '更多',
      aboutLove21: '关于 Love 21 ↗',
      annualReport: '年度报告 ↗',
    },
    community: {
      eyebrow: '社群 · 实证与认识',
      title: '能力，早已盛大。',
      subhead:
        '学员的真实时刻——以及说明这份工作为何重要的事实。没有独立的「认识」页；社群本身就是课堂。',
      filterAll: '全部',
      filters: {
        sport: '运动',
        art: '艺术／音乐／舞蹈',
        nutrition: '营养',
        family: '家庭',
        fitness: '体能',
        special: '特别活动',
        outings: '外出',
        csr: '企业社会责任',
      },
      shareCta: '分享一个时刻',
      shareTitle: '分享一个时刻',
      shareHint: '用自己的话分享一个真实时刻——一小段文字就足够。',
      shareAsLabel: '以此身份发布',
      shareAuthorLabel: '你的姓名',
      shareAuthorPlaceholder: '例如：陈大文',
      shareEmailLabel: '邮箱（可选）',
      shareEmailPlaceholder: '方便我们在公开时通知你',
      shareEmailInvalid: '请输入有效邮箱，或留空。',
      sharePhoto: '照片',
      sharePhotoAdd: '加入照片',
      sharePhotoAttached: '已附上照片',
      sharePhotoRemove: '移除照片',
      sharePhotoUploading: '正在上传照片…',
      sharePhotoTooLarge: '图片超过 5MB，请选择较小的档案。',
      sharePhotoWrongType: '请选择 JPEG、PNG 或 WebP 图片。',
      sharePhotoFailed: '照片上传失败，请再试一次。',
      shareLine: '你的故事',
      shareLinePlaceholder: '例如：与全队一起完成比赛，互相击掌庆祝。',
      shareLengthHint: '至少需要 {min} 个字——目前 {n} 个',
      shareActivityLabel: '这是关于什么的？',
      shareActivityHint: '这会成为卡片上的标签，以及它所属的分页。',
      shareRelationshipLabel: '你与 Love 21 的关系',
      relationships: {
        volunteer: '志愿者',
        parent: '家长或家人',
        supporter: '支持者',
      },
      shareConsent: '我已获得许可，可公开分享这张照片与故事。',
      shareError: '发生错误，请再试一次。',
      shareReviewNote: '贴文须经审核才会公开。',
      shareSubmit: '提交审核',
      shareClose: '关闭',
      shareSent: '已提交审核——谢谢。',
      knowledgeHook: '想和他们一起试试？→ 做义工',
      dotsCaption: '700 名婴儿 · 点亮 1 个',
      sliderGuess: '拖动猜猜有多少',
      sliderReveal: '显示真实数字',
      sliderYourGuess: '你的猜测',
      sliderReal: '真实数字',
      sliderUnit: '种活动',
      emptyFilter: '此项目暂无时刻——试试其他筛选。',
      momentsLabel: '个能力时刻，持续累积中',
      celebrateCta: '庆祝',
      instagramLabel: '来自 Instagram',
      instagramTag: 'Instagram',
      instagramCta: '在 Instagram 上查看',
      pagePrev: '上一页',
      pageNext: '下一页',
      showingRange: '显示 {total} 则中的第 {from}–{to} 则',
      photoAlt: 'Love 21 学员参与活动的照片',
      imageLabel: '照片',
      timeToday: '今天',
      timeDayAgo: '{n} 天前',
      timeDaysAgo: '{n} 天前',
      timeWeekAgo: '{n} 周前',
      timeWeeksAgo: '{n} 周前',
      timeMonthAgo: '{n} 个月前',
      timeMonthsAgo: '{n} 个月前',
      stayClose: {
        eyebrow: '保持联系',
        title: '想创造更多故事吗？',
        body: '在收件箱中接收 Love 21 最新消息，或探索加入我们社群的不同方式。',
        emailLabel: '电邮地址',
        emailPlaceholder: '电邮地址',
        subscribe: '订阅',
        subscribed: '谢谢 — 邮件名单上线后我们会再联系你。',
        volunteer: '成为志愿者',
        donate: '捐款',
        partner: '合作',
      },
    },
    mediaNews: {
      eyebrow: '更长的故事',
      title: '想看更多故事？',
      subhead: '更长的文章与媒体报道都在我们的文章页。',
      cta: '浏览文章',
      readMore: '阅读全文',
      prevSlide: '上一则',
      nextSlide: '下一则',
      pause: '暂停轮播',
      play: '播放轮播',
      slideLabel: '第 {n} 则，共 {total} 则',
    },
    articlesPage: {
      eyebrow: '媒体与新闻',
      title: '文章',
      subhead: 'Love 21 的长篇故事与媒体报道——来自新闻室与我们的社群。',
      ourStories: '来自 Love 21',
      ourStoriesLede: '由基金会撰写，可在此阅读。',
      readArticle: '阅读文章',
      backToCommunity: '返回社群',
    },
    volunteer: {
      kicker: '参与',
      title: '现身。认识他们。',
      subhead: '面对面，偏见才会缩小。选一节课，带上你的能量——一起参与，不是旁观。',
      communityLink: '先看看社群',
      teachingNote:
        '如果你希望为我们的受惠者开办每周课堂，或支援现有课堂，请联络我们的计划经理 Kenneth：',
      teachingEmail: 'maggie@love21foundation.com',
      teachingKicker: '教学义工',
      modeTitle: '你想怎样参与？',
      individualTag: '个人',
      individualTitle: '报名或协助课堂',
      individualBody: '以参与者身份加入一节课。HandsOn 与 Love 21 课堂，集中在此。',
      individualCta: '浏览课堂',
      corporateTag: '企业',
      corporateTitle: '企业义工与捐助',
      corporateBody: '团队义工——非洲鼓、Zumba、烹饪、艺术。联系我们，一起策划。',
      corporateCta: '企业查询',
      skillsTitle: '你能带来什么？',
      skillsHint: '可选 — 点选筛选。',
      skills: {
        patient: '有耐心',
        sports: '运动',
        music: '音乐',
        kitchen: '厨房',
        photography: '摄影',
        youth14: '青少年 14+',
        cantonese: '粤语（可选）',
      },
      clearSkills: '清除筛选',
      filterMySkills: '按我的技能筛选',
      filterMySkillsHint: '显示符合你个人档案已保存技能的课堂。',
      filterMySkillsEmpty: '请先在「我的影响力」加入技能，再回来筛选。',
      filterMySkillsEdit: '编辑我的技能',
      filterMySkillsLogin: '登录后可按已保存技能筛选',
      listTitle: '开放课堂',
      emptyList: '没有符合这些技能的课堂——试试清除筛选。',
      emptyListNoSessions: '目前没有开放课堂。稍后再看，或向 Love 21 查询即将举行的班。',
      loadError: '无法从服务器加载课堂。请确认 API 正在运行，然后刷新。',
      recruiting: '招募中',
      fullBadge: '已满',
      spots: '{filled}/{capacity} 名额',
      sourceLove21: 'Love 21',
      sourceHandson: 'HandsOn',
      viewDetail: '查看课堂',
      backToHub: '所有课堂',
      detailWhat: '你实际会做什么',
      detailEligibility: '谁可以参加',
      detailSafeguard:
        '保护措施：教练会在场。首次课堂前我们可能请你简单自我介绍——完整流程仍与 Love 21 敲定中。',
      handsonCapacity:
        'HandsOn：已订 {filled}/{capacity} · 此处有兴趣 {interested} 人',
      registerInterest: '登记兴趣',
      completeHandson: '亦可在 HandsOn 报名（可选）',
      joinSession: '加入课堂',
      formIntro:
        'Love 21 为香港注册慈善机构，致力透过运动、营养及全方位支援计划，支持唐氏综合症、自闭症及神经多样性社群。我们现正寻找充满热诚的义工！',
      interestFormIntroLoggedIn:
        '你已登录——我们会使用你已保存的义工资料。确认安全守则即可登记兴趣。',
      shortFormIntro: '快速报名——有位即确认，无需职员审批。',
      shortFormIntroLoggedIn: '你已登录——确认年龄组别及安全守则即可预留名额。',
      joiningAs: '以 {name} · {email} 报名',
      joiningAsEdit: '更新个人资料',
      shortName: '全名',
      shortSubmit: '确认我的名额',
      safeguardAck: '我明白会以主动帮手身份参与，现场有教练，并会跟从课堂简介（包括紧急步骤）。',
      emergencyName: '紧急联络人姓名',
      emergencyPhone: '紧急联络人电话',
      fullError: '此课堂已满——请选其他班。',
      signupError: '未能保存报名，请再试。',
      signupDuplicate: '你已报名此课堂。',
      interestChineseName: '中文全名',
      interestEnglishName: '英文全名',
      interestAgeGroup: '年龄／人口组别',
      ageGroups: {
        youth14_18: '青年义工（14–18）',
        age19_29: '19–29 岁',
        age30_44: '30–44 岁',
        age45_59: '45–59 岁',
        age60_plus: '60 岁或以上',
      },
      ageGroupHint: '帮助 Love 21 了解义工人口结构——不用作推广。',
      interestGender: '性别',
      genders: {
        female: '女',
        male: '男',
        prefer_not: '不透露',
      },
      interestEmail: '联络电邮',
      interestPhone: '联络电话',
      interestRoles: '请问你对哪一个义工角色感兴趣？（可选多项）',
      roles: {
        assistant: '我想以助教身份参与现有课堂',
        host: '我想自己带领一个课堂',
        event: '我想成为大型活动义工',
        other: '其他',
      },
      interestRoleOther: '请注明其他角色',
      interestAbout: '告诉我们你的喜好和专长吧！',
      interestDiscovery: '请问你从什么渠道知道 Love 21 的义工机会？',
      discovery: {
        existing: '一向有参加 Love 21 义工活动',
        social: '社交媒体',
        edm: '通讯电邮',
        company: '公司',
        other: '其他',
      },
      interestDiscoveryOther: '请注明',
      interestSubmit: '提交义工报名',
      interestCancel: '取消',
      interestDuplicate: '你已对此课堂登记兴趣。',
      interestError: '无法保存你的兴趣。请确认 API 正在运行，然后再试。',
      hubSignupTitle: 'Love 21 义工报名',
      hubSignupSubhead: '上方选课堂最快捷——或在此使用完整兴趣表格。',
      hubSignupCta: '打开报名表格',
      hubCreateAccountCta: '改为创建账户',
      hubSignedInTitle: '你已登录',
      hubSignedInSubhead:
        '在上方选一节课，用你已保存的资料报名。可随时在「我的影响力」更新义工档案。',
      hubSignedInCta: '我的义工档案',
      joinConfirmTitle: '加入这个课堂？',
      joinConfirmBody: '我们会为你确认名额并开启课堂简介。',
      joinConfirmYes: '好，我参加',
      joinConfirmNo: '先不要',
      successTitle: '你已报名「{session}」。',
      successBody: '名额已确认。出发前请打开简短简介——如想支持课堂也可捐助。',
      successGiveCta: '以捐助支持',
      successHome: '返回首页',
      successBriefingCta: '打开课堂简介',
      successSaveCta: '保存课堂到「我的影响」',
      briefingKicker: '出发前',
      briefingTitle: '你的课堂简介',
      briefingArrive: '到达时间',
      briefingMeet: '集合点',
      briefingWear: '穿着／携带',
      briefingDo: '你会做什么',
      briefingEmergency: '紧急情况',
      briefingCancel: '若不能出席',
      corporatePanelTitle: '企业义工',
      corporateBullets: [
        '非洲鼓工作坊',
        'Zumba 健身课',
        '健康烹饪班',
        '与学员一起做手工艺术',
      ],
      corporateFormTitle: '告诉我们你的团队',
      corporateOrg: '机构名称',
      corporateContact: '联络人',
      corporateEmail: '公司电邮',
      corporateMessage: '你们希望做什么？',
      corporateSubmit: '送出查询',
      corporateThanks: '谢谢——我们会以电邮回复。',
      changeMode: '选择另一条路',
    },
    give: {
      kicker: '支持',
      title: '有意义的捐助',
      subhead: '金钱、物资，或让朋友一起参与的筹款——你的捐助让会员计划保持免费。',
      tabMoney: '捐款',
      tabWishlist: '心愿清单',
      tabFundraise: '筹款',
      amountLabel: '你的捐款（港币）',
      customAmountLabel: '或输入任何金额',
      customAmountHint: '每一元都有意义 — 可由港币 1 元起。',
      everyDollarCounts: '每一元都有意义！',
      impactLabel: '这笔捐款能成为',
      impactSmall: '每一元都帮助会员计划保持免费。',
      once: '一次过',
      weekly: '每周',
      monthly: '每月',
      programmeLabel: '可选计划',
      receiptNote:
        '捐款港币 100 元或以上，可应要求发出正式收据并邮寄。查询请联络 Maggie：Maggie@love21foundation.com。',
      otherMeansTitle: '其他捐款方式',
      otherMeansBank: '汇丰银行过数：582-350526-838 · FPS ID：164778151',
      otherMeansCheque: '支票抬头：「Love 21 Foundation Limited」。',
      otherMeansAddress:
        '邮寄地址：香港九龙新蒲岗六合街 21 号 Artisan Lab 11 楼 1102 室。',
      programmes: {
        sports: '运动',
        fitness: '体能',
        nutrition: '营养',
        family: '家庭',
        where_needed: '最需要的地方',
      },
      section88: '港币 100 元或以上捐款可根据第 88 条申请扣税。',
      trustStrip: '约 86% 资金用于计划（年度报告）。',
      emailLabel: '接收更新的电邮',
      emailHint: '若选择礼物旅程更新则需要（代替 Stripe 结账电邮）。',
      emailRequiredJourney: '请填写电邮以选择旅程更新。',
      receiptTitle: '正式收据（第 88 条）',
      receiptUseAccount: '使用我的账户资料开立收据',
      receiptUseAccountHint: '收据会电邮至你的登录电邮。',
      receiptNameLabel: '收据上的全名',
      receiptEmailLabel: '收据电邮',
      receiptEmailHint: '正式收据会寄至此电邮。若选择旅程更新，也会寄到此地址。',
      receiptForOther: '以他人名义开立收据',
      receiptForOtherHint: '适用于不同纳税人（例如配偶或公司）。收据姓名应与申请扣税者一致。',
      receiptRequired: '请填写正式收据所需的姓名与电邮。',
      applyCustom: '套用',
      journeyOptInLabel: '电邮通知我这笔捐款的去向',
      journeyOptInHelper: '已收到 → 配对计划 → 课堂发生时。只限捐款用途更新，不是通讯。',
      journeyTitle: '你的捐款去向',
      journeyReceived: '已收到',
      journeyMatched: '已配对计划',
      journeySession: '课堂更新',
      journeyEmailNote: '有消息时会电邮 {email}。',
      journeyAdvance: '查看下一则更新',
      donateCta: '捐款',
      donateWorking: '处理中…',
      wishlistTitle: '心愿清单',
      wishlistSubhead: '认捐计划所需物资——我们会电邮说明如何送交或自取。',
      needed: '需要 {n}',
      pledged: '已认捐 {n}',
      pledgeCta: '认捐',
      pledgeTitle: '认捐此项目',
      pledgeQty: '数量',
      pledgeNote: '备注（可选）',
      pledgeSubmit: '送出认捐',
      pledgeSuccess: '我们会电邮说明如何送交或自取。',
      pledgeClose: '关闭',
      wishlistEmpty: '目前心愿清单没有项目。',
      fundraiseTitle: '发起筹款',
      fundraiseSubhead: '三步：建立、等候审批，然后分享并查看进度。',
      fundraiseSteps: ['建立页面', '我们审批', '分享并查看进度'],
      createCampaignCta: '开始筹款',
      liveCampaigns: '进行中的筹款',
      noLiveCampaigns: '尚未有已批准的筹款。',
      yourCampaigns: '你的筹款',
      noCampaigns: '尚未有筹款——请在上方建立。',
      formTitle: '筹款标题',
      formStory: '你的故事',
      formGoal: '目标（港币）',
      formCover: '封面图片',
      formEnd: '结束日期',
      formSubmit: '提交审批',
      formWorking: '提交中…',
      formError: '无法建立筹款，请再试一次。',
      campaignProgress: '已筹 HK${raised}／目标 HK${goal}',
      campaignShare: '复制链接',
      campaignShareDone: '已复制链接',
      campaignDonate: '捐给此筹款',
      campaignPending: '等候审批',
      campaignApproved: '已批准',
      campaignRejected: '已拒绝',
      campaignNotFound: '找不到此筹款。',
      campaignAwaitingApproval: '此筹款正等候 Love 21 审批，通过后才可接受捐款。',
      stickyDonate: '捐款',
      thanksAck: '谢谢你。你的捐助帮助会员计划保持免费。',
      thanksNotifyLabel: '有这笔捐款如何被使用的消息时，电邮通知我。',
      thanksNotifyHelper: '只在真实事情发生时——例如一节课举行了。不会滥发电邮。',
      thanksEmail: '电邮',
      thanksNotifyToast: '你会在 {email} 收到更新',
      thanksSampleUpdate: '演示更新：「你的捐助帮助周六舞蹈班得以举行。」',
      thanksCreateAccount: '想把捐助与义工时数放在同一处？',
      thanksCreateAccountBody: '用此电邮建立免费账户——我们会自动附上这笔捐助。',
      thanksCreateCta: '建立账户',
      thanksNoThanks: '不用了——电邮更新已足够',
      thanksExistingBody: '我们找到此电邮的账户——这笔捐助已在账户上。',
      thanksViewGiving: '查看你的捐助',
      thanksVolunteer: '做义工',
      thanksShareCampaign: '分享筹款',
      thanksHome: '首页',
      thanksSaveImpact: '保存捐助到「我的影响」',
    },
    login: {
      kicker: '欢迎回来',
      signInTitle: '登录',
      signUpTitle: '创建账户',
      subhead: '在同一处查看义工课堂与捐助。捐款不必先登录。',
      modeLabel: '账户模式',
      signInTab: '登录',
      signUpTab: '注册',
      fullName: '英文全名',
      chineseName: '中文全名',
      phone: '联络电话',
      volunteerProfileHint: '会保存到义工档案，之后课堂报名更简短。',
      email: '电邮',
      password: '密码',
      signInCta: '登录',
      signUpCta: '创建账户',
      working: '处理中…',
      genericError: '出了点问题，请再试一次。',
      notConfigured: '此环境尚未设置 Supabase Auth。',
      checkEmail:
        '账户已创建。请先确认 Supabase 电邮链接，然后登录。（演示可在 Authentication → Providers → Email 关闭 Confirm email。）',
      memberHandoffNote:
        '不是义工或捐款人？在找课堂时间表或 Love 21 家庭活动？',
      memberHandoffCta: '前往 Love 21 家庭专区 →',
      backToMe: '返回我的影响',
    },
    me: {
      kicker: '你的支持变成了什么',
      title: '我的影响',
      subhead:
        '先看合并故事——细节在「义工」与「捐助」。这是支持者页，不是会员 App。',
      tabImpact: '总览',
      tabVolunteer: '义工',
      tabGiving: '捐助',
      tabAccount: '账户',
      overviewLead:
        '学习、时数与捐助长成同一座花园。你资助的课堂真正举行时，证明收据会出现在此。',
      loading: '正在加载你的影响…',
      gateTitle: '登录以查看你的影响',
      gateBody: '创建免费账户，把捐助、时数与证明收据放在同一处。捐款仍可不登录。',
      gateCta: '登录',
      hello: '已登录',
      logOut: '登出',
      gardenKicker: '合并故事',
      gardenTitle: '学习、现身、捐助——一起成长',
      gardenBody:
        '这棵树随你的故事成长——读过的故事、义工时数、金钱捐助与物资认捐。「义工」与「捐助」页有详细列表。',
      gardenGiven: '已捐',
      gardenGifts: '笔数',
      gardenClasses: '资助课堂',
      gardenHours: '义工时数',
      gardenLearn: '已读故事',
      gardenItems: '已认捐物资',
      gardenPillarHint: '成长顺序：学习 → 义工 → 捐助（金钱与物资清单）。',
      gardenLearnCta: '到新闻学习 →',
      gardenVolunteerCta: '寻找课堂 →',
      gardenGiveCta: '金钱捐助 →',
      gardenItemsCta: '认捐物资 →',
      receiptsKicker: '证明收据',
      receiptsTitle: '当你资助的课堂真正举行',
      receiptsBody: '不是捐助列表——而是你帮助保持免费的课堂真正举行时的一则通知。只有人数；从不具名。',
      receiptsEmpty: '尚未有证明收据。当你资助的免费课堂举行时会显示在此。',
      receiptsDeidentified: '已去识别 · 不分享姓名',
      conversionKicker: '自然下一步',
      conversionMonthlyTitle: '成为每月捐助者？',
      conversionMonthlyBody: '稳定捐助让下一双周的课堂保持免费——不是计算器，是延续。',
      conversionMonthlyCta: '每月捐助',
      conversionHoursTitle: '你已付出 {hours} 小时——成为每月捐助者？',
      conversionHoursBody: '你已现身。每月捐助让课堂之间的计划保持免费。',
      conversionTermTitle: '再一堂，就凑齐一整期',
      conversionTermBody: '你大约已有港币 ${toward}，朝向港币 ${cost} 的课堂基金。再一笔可完成。',
      conversionTermCta: '资助一堂',
      conversionFirstTitle: '把时数化成持续支持',
      conversionFirstBody: '你已在现场付出 {hours} 小时。第一笔捐助帮助下一堂对会员免费。',
      conversionFirstCta: '捐助',
      accountKicker: '账户与同意',
      accountTitle: '我们如何联络你',
      accountBody: '个人资料、语言、旅程更新与同意——随时可改。',
      accountProfile: '个人资料',
      accountEmail: '电邮',
      accountName: '姓名',
      accountLanguage: '语言',
      accountLanguageHint: '套用至此装置上的整个网站。',
      accountNotifications: '通知',
      accountNotificationsHint: '资助课堂举行时的旅程通知——不是电子报轰炸。',
      accountJourneyOptIn: '捐助用途更新',
      accountJourneyOptInHint: '当我资助的免费课堂实际举行时通知我。',
      accountEmailOptIn: '电邮提醒',
      accountEmailOptInHint: '偶尔关于课堂与认可的讯息——不会滥发。',
      accountConsent: '同意',
      accountConsentHint: '证明收据从不具名会员。照片同意另行、可选。',
      accountPhotoConsent: '我可出现在支持者故事中（可选）',
      accountPhotoConsentHint: '仅在你镜头前义工且职员核实照片时。可随时撤回。',
      accountSaved: '偏好已保存',
      volunteerKicker: '义工档案',
      volunteerTitle: '你的义工服务',
      volunteerEmpty: '尚未有课堂。报名后，时数与认可会显示在此。',
      volunteerCta: '寻找课堂',
      volunteerMoreCta: '再参加一节',
      volunteerHoursNote: '此处时数来自本站 Love 21 课堂报名——不是 HandsOn 预约。',
      skillsTitle: '你的技能',
      skillsHint: '会保存到个人档案。在义工页可开启「按我的技能筛选」配对课堂。',
      skillsSave: '保存技能',
      skillsSaved: '已保存技能',
      skillsNeedEmail: '请用电邮登录以永久保存技能。',
      statSessions: '课堂',
      statHours: '时数',
      statProgrammes: '计划',
      sessionsTitle: '你的课堂',
      interestsTitle: '你的兴趣登记',
      interestsLead: '你在此登记的 HandsOn 兴趣——若为外部课堂，仍须在 HandsOn 完成报名。',
      interestRegistered: '已登记兴趣',
      sessionConfirmed: '已确认',
      sessionAttended: '已出席',
      sessionNoShow: '缺席',
      sessionApplied: '已申请',
      openBriefing: '课堂简介',
      feedbackTitle: '这次课堂感觉如何？',
      feedbackLead: '可选填——帮助 Love 21 改进下一次。',
      feedbackRating: '整体体验（1–5）',
      feedbackWouldReturn: '你会再来当义工吗？',
      feedbackWouldReturnYes: '会',
      feedbackWouldReturnNo: '不会',
      feedbackNote: '有什么可以改进？（可选）',
      feedbackNotePlaceholder: '简短留言即可',
      feedbackSubmit: '送出意见',
      feedbackSubmitting: '传送中…',
      feedbackThanks: '谢谢你的意见',
      feedbackError: '未能保存——请至少填一项，或稍后再试。',
      badgesTitle: '认可',
      badgesSubhead: '为出席而设——有助履历与 CSR，不是积分游戏。',
      badgeEarned: '已获得',
      badgeLocked: '下一步',
      giveCta: '捐助',
      givingTitle: '你的捐助',
      givingSubhead:
        '每笔捐助的旅程——收到、扎根、课堂成长。总览是学习、时数与捐助的合并故事。',
      givingEmpty: '尚未有捐助。每一元都帮助会员计划保持免费。',
      viewGift: '查看捐助',
      journeyReceived: '已收到捐助',
      journeyMatched: '已扎根于计划',
      journeySession: '课堂已成长',
      journeyStatusDone: '完成',
      journeyStatusProcessing: '仍在成长',
      journeyStatusWaiting: '尚未开始',
      journeyGrowthLabel: '成长 {n}／3',
      journeyGrowthCumulativeTitle: '你的影响成长',
      journeyGrowthCumulativeBody:
        '所有捐助合成一棵树——从首笔捐助、配对基金到课堂真正举行，透过运动、营养与关怀，帮助会员发挥自己的能力。',
      journeyGrowthCumulativeLabel: '累积成长 {n}／4',
      journeyGrowthTotalGiven: '已捐',
      journeyGrowthGiftCount: '笔数',
      journeyGrowthSessions: '课堂',
      journeyDetailReceivedDone: 'Love 21 已记录你的捐助，正待分配至计划基金。',
      journeyDetailReceivedProcessing: '正在确认付款到账——通常于结账后一天内完成。',
      journeyDetailReceivedWaiting: '等候记录捐助。',
      journeyDetailMatchedDone:
        '已拨入「{programme}」计划基金——用于教练、场地与物资，让会员可免费参加。',
      journeyDetailMatchedProcessing:
        '职员正于本双周把这笔捐助拨入「{programme}」基金（约 80–86% 直接用于计划）。',
      journeyDetailMatchedWaiting: '收到后会把这笔捐助扎根于「{programme}」——不是一般电子报。',
      journeyDetailSessionDone: '已举行一节「{programme}」会员课堂。你的捐助有助该日保持免费。',
      journeyDetailSessionDoneNamed: '「{title}」已于 {when} 举行。你的捐助有助该课堂保持免费。',
      journeyDetailSessionProcessing:
        '等候下一节「{programme}」课堂——举行时会收到捐助用途通知，不是电子报。',
      journeyDetailSessionWaiting: '配对后，当这笔捐助支持的「{programme}」课堂实际举行时会通知你。',
    },
    support: {
      eyebrow: '支援',
      title: '想为你的家庭寻找支援？',
      intro:
        'Love 21 在香港为唐氏综合症、自闭症及其他神经多样人士提供运动、营养及家庭支援活动。如果你觉得我们可能适合你的家庭，我们很乐意与你见面。',
      processTitle: '告诉我们你的家庭情况',
      processBody:
        '填写一份简短表格，我们的团队会尽快联系你，了解你家庭的需要。',
      formCta: '填写表格',
      emailNote: '想用邮件？请写信到 info@love21foundation.com',
      memberNote: '已经是 Love 21 家庭？',
      memberCta: '登录查看你的课堂',
      backHome: '返回首页',
    },
    admin: {
      kicker: '职员',
      hubTitle: '职员中心',
      accessDenied: '无法访问',
      accessDeniedBody:
        '此区需要管理员账号。请用职员账号登录，或请同事将你的 profiles.role 设为 admin。',
      signedInAs: '已登录：{email} · API 角色：{role}',
      signOutRetry: '登出后再试',
      backHome: '← 首页',
      verifyError: '无法核实管理员角色。',
      navOverview: '总览',
      navOverviewHint: '指标与今日待办',
      navArticles: '文章',
      navArticlesHint: '撰写与发布新闻',
      navStories: '故事台',
      navStoriesHint: '批准相片并复制文案',
      navCampaigns: '筹款',
      navCampaignsHint: '审批社区筹款活动',
      navAttendance: '点名',
      navAttendanceHint: '记录出席',
      navModeration: '声音审核',
      navModerationHint: '审核支持者故事',
      storiesTitle: '故事台',
      storiesIntro:
        '批准可公开使用的课堂相片，再把草稿文案复制到 Instagram 或 Facebook。批准会产生文案草稿；未获同意的面孔会保持模糊——本站不会发布到 Meta。',
      storiesMetaNote: '复制文案／打开 Instagram——实际发布请在 Instagram 或 Facebook App 完成。',
      storiesLoadError: '无法加载故事台。',
      storiesApproveError: '批准失败。',
      storiesApproved: '已批准——文案草稿在下方。',
      storiesCopied: '已复制文案——请自行贴到 Instagram 或 Facebook。',
      storiesCopyFailed: '复制失败——可改下载。',
      storiesReminded: '已设定提醒：{when}——仍须在 App 发布。',
      storiesScheduleError: '无法设定提醒。',
      storiesUnavailable:
        '故事台需要套用 session_proofs／social_drafts 迁移（20260802_1130）。套用前此队列为空。',
      storiesApproveHeading: '1 · 批准课堂相片',
      storiesApproveLead: '仅职员可批准。同意状态决定显示哪些面孔；未获同意者不会公开。',
      storiesNoPending: '没有待批相片。批准后草稿会出现在下方。',
      storiesBlurActive: '自动模糊中',
      storiesMembers: '{visible} 可见 · {blurred} 已模糊',
      storiesApproveCta: '批准并建立草稿',
      storiesFanoutHeading: '批准后会产生',
      storiesWebsiteStory: '网站故事',
      storiesCaptionDrafts: '文案草稿',
      storiesCaptionsHeading: '2 · Instagram 与 Facebook 文案草稿',
      storiesCaptionsLead:
        '复制或下载后，在 Instagram 或 Facebook App 粘贴。提醒时间只是备注——本中心不会发布到 Meta。',
      storiesOpenInstagram: '打开 @love21foundation Instagram',
      storiesCopyHashtags: '复制建议标签',
      storiesNoDrafts: '尚无文案草稿——请先批准上方相片。',
      storiesReminder: '提醒',
      storiesCopyCaption: '复制文案',
      storiesDownload: '下载 .txt',
      storiesRemind: '明天提醒我',
      consentCleared: '所有面孔已获同意',
      consentPartial: '部分——未同意面孔已模糊',
      consentNone: '无面孔同意——全部模糊',
      articlesTitle: '文章',
      articlesIntro: '建立、编辑并发布新闻、教育与报告。正文存成段落区块；双语栏位为英文与繁体中文。',
      articlesNew: '新增文章',
      articlesEdit: '编辑',
      articlesEmpty: '尚无文章。',
      articlesUnavailable: '文章管理需要先套用 articles 数据表迁移。',
      articlesLoadError: '无法加载文章。',
      articlesSaveError: '无法保存文章。',
      articlesTitleRequired: '英文标题为必填。',
      articlesSaved: '已保存。',
      articlesCreated: '草稿已建立。',
      articlesPublished: '已发布。',
      articlesUnpublished: '已退回草稿。',
      articlesSave: '保存',
      articlesPublish: '发布',
      articlesUnpublish: '取消发布',
      articlesCancel: '取消',
      articlesFieldCategory: '类别',
      articlesFieldFeatured: '首页精选',
      articlesFieldTitleEn: '标题（英文）',
      articlesFieldTitleZh: '标题（繁体中文）',
      articlesFieldExcerptEn: '摘要（英文）',
      articlesFieldExcerptZh: '摘要（繁体中文）',
      articlesFieldBodyEn: '正文（英文）',
      articlesFieldBodyZh: '正文（繁体中文）',
      articlesFieldAuthor: '作者',
      articlesFieldCover: '封面图片网址',
      articlesBodyHint: '段落之间空一行。会存成段落区块。',
      moderationTitle: '声音审核',
      moderationIntro: '新闻「声音」分页的支持者与家庭故事。批准后公开，拒绝则不上网。',
      campaignsTitle: '筹款',
      campaignsIntro: '审批社区筹款活动，通过后才公开。',
      attendanceTitle: '点名',
      attendanceIntro: '为即将举行的课堂记录义工出席。',
      dashboardTitle: '总览',
      dashboardIntro: '即时指标与今日待办。',
      dashboardTileDonations: '捐款',
      dashboardTileSessions: '即将举行的课堂',
      dashboardTileInterests: '兴趣登记',
      dashboardTilePending: '待办',
      dashboardGiftsEmpty: '此期间尚无捐款',
      dashboardGiftsHint: '{n} 笔捐款 · 网站渠道',
      dashboardSpotsHint: '{n} 个空位',
      dashboardInterestsHint: 'HandsOn 兴趣登记——与课堂时数分开计算',
      dashboardPendingHint: '故事台、筹款与声音审核',
      dashboardChartMoney: '捐款金额',
      dashboardChartMoneyDesc:
        '过去六个月网站与个人捐款（港元）。这不是爱二十一全年港币 1,350 万收入——计划开支仍占支出约 86%。',
      dashboardChartMoneyUnit: '每月港元',
      dashboardChartMoneyEmpty: '此期间尚无捐款',
      dashboardChartHours: '义工时数',
      dashboardChartHoursDesc:
        '过去六个月在本站记录的爱二十一课堂时数。HandsOn 兴趣登记分开显示，从不合计。',
      dashboardChartHoursUnit: '每月时数',
      dashboardChartHoursEmpty: '此期间尚无时数',
      dashboardQueueTitle: '今日待办',
      dashboardQueueIntro: '故事台、点名、筹款、声音与影响数字——依目前等候项目列出。',
      dashboardQueueOpen: '开启',
      dashboardFunnelTitle: '兴趣 → 报名 → 捐款',
      dashboardFunnelIntro: '本站表单累计——不是匿名访客分析',
      dashboardFunnelDropoffs: '阶段之间的最大落差',
      dashboardFunnelSources: '他们如何找到我们',
      dashboardFunnelSourcesHint: '来自义工与捐款表单的自我回报——不是广告追踪代码。',
      dashboardFunnelEmpty: '尚无兴趣登记、报名或捐款。',
      dashboardFunnelSourcesEmpty: '尚无来源或转介答案。',
    },
  },
}

function deepMerge(base, over) {
  const out = { ...base }
  for (const key of Object.keys(over)) {
    const b = base[key]
    const o = over[key]
    if (
      o &&
      typeof o === 'object' &&
      !Array.isArray(o) &&
      b &&
      typeof b === 'object' &&
      !Array.isArray(b)
    ) {
      out[key] = deepMerge(b, o)
    } else if (o !== undefined) {
      out[key] = o
    }
  }
  return out
}

const EASY_READ_EN = {
  // Keep nav labels stable (Community stays Community) — only body copy simplifies.
  hero: {
    eyebrow: 'Love 21',
    line1: 'So much',
    line2: 'ability',
    subhead:
      'We are a Hong Kong charity. We support people with Down syndrome, autism and other neurodiverse needs through sport, food and care.',
    cta: 'See what they can do',
  },
  stats: {
    title: 'Our numbers',
    updated: 'From our 2024–25 annual report.',
    items: [
      { id: 'families', value: 490, suffix: '', label: 'families we help' },
      { id: 'sessions', value: 6859, suffix: '', label: 'classes each year' },
      { id: 'activityTypes', value: 84, suffix: '', label: 'kinds of activities' },
      { id: 'volunteerHours', value: 1000, suffix: '+', label: 'volunteer hours each month' },
    ],
  },
  activities: {
    title: 'Coming soon',
    subhead: 'You can join a class. Or you can come and watch.',
    recruiting: 'We need helpers',
    joinCta: 'Help at this class',
    viewCta: 'See this class',
  },
  spotlight: {
    title: 'What people can do',
    subhead: 'These are real stories.',
    reveal: 'Meet',
    readMore: 'Read more',
  },
  paths: {
    title: 'Ready to make a difference?',
    subhead: 'Choose one.',
    witness: {
      tag: 'Look',
      title: 'See our stories',
      body: 'Read about people and what they can do.',
      cta: 'Go to stories',
    },
    take: {
      tag: 'Help',
      title: 'Be a volunteer',
      body: 'Come to a class and help.',
      cta: 'Volunteer',
    },
    support: {
      tag: 'Give',
      title: 'Give money',
      body: 'Your money helps pay for free classes.',
      cta: 'Donate',
    },
  },
  footer: {
    tax: 'Love 21 is a charity in Hong Kong. Gifts of HK$100 or more can get tax relief.',
    portal: 'Member website',
    support: 'Get help',
    followUs: 'Find us online',
    rights: 'All rights reserved.',
  },
  community: {
    eyebrow: 'Stories',
    title: 'What people can do',
    subhead: 'Read short stories. Learn facts. Share a moment if you want.',
    momentsLabel: 'good moments. And counting.',
  },
  volunteer: {
    kicker: 'Help out',
    title: 'Come and help',
    subhead: 'Meet our members. Help at a class.',
    communityLink: 'Read stories first',
    modeTitle: 'How do you want to help?',
    individualTag: 'One person',
    individualTitle: 'I want to help',
    individualBody: 'Pick a class and sign up.',
    individualCta: 'Find a class',
    corporateTag: 'A company',
    corporateTitle: 'My company can help',
    corporateBody: 'Tell us. We will contact you. We do not book online.',
    corporateCta: 'Contact us',
  },
  give: {
    kicker: 'Give',
    title: 'Give to Love 21',
    subhead: 'Give money. Or give things. Or raise money with friends.',
    demoBanner: 'This is a demo. No real money is taken.',
    tabMoney: 'Money',
    tabWishlist: 'Things we need',
    tabFundraise: 'Raise money',
    thanksAck: 'Thank you. Your gift helps keep classes free.',
    thanksNotifyLabel: 'Email me when you use my gift.',
    thanksNotifyHelper: 'We only email when something real happens. Not spam.',
    thanksNoThanks: 'No thanks. Email updates are enough.',
    thanksCreateAccount: 'Want gifts and volunteer hours in one place?',
    thanksCreateAccountBody: 'Make a free account with this email. We will add this gift.',
    thanksCreateCta: 'Make an account',
  },
  support: {
    eyebrow: 'Support',
    title: 'Need help for your family?',
    intro: 'Love 21 helps people with Down syndrome, autism, and other needs. We do sport, food help, and family support.',
    processTitle: 'Tell us about you',
    processBody: 'Fill in a form. We will contact you soon.',
    formCta: 'Fill in the form',
    emailNote: 'Or email us',
    memberNote: 'Already a Love 21 family?',
    memberCta: 'Sign in',
    backHome: 'Home',
  },
  login: {
    memberHandoffNote:
      'Not a volunteer or donor? Looking for classes or Love 21 family events?',
    memberHandoffCta: 'Go to the Love 21 family portal →',
  },
}

/** Standard copy, or UK Easy Read overlay when easyRead is on (EN first; zh falls back). */
export function getStrings(locale, easyRead) {
  const base = STRINGS[locale]
  if (!easyRead) return base
  if (locale === 'en') return deepMerge(base, EASY_READ_EN)
  // Traditional / Simplified: keep structure; still apply EN easy nav labels lightly via layout
  return deepMerge(base, {
    nav: { easyRead: locale === 'zh-Hans' ? '简易阅读' : '簡易閱讀' },
  })
}

